// AUTO-GENERATED by scripts/build_course_data.py — do not edit by hand.
// Member-only course data: bundled into the serverless function, never in public/.
const airbnb = {
 "id": "airbnb",
 "title": "The Airbnb Playbook",
 "subtitle": "Buy, launch and run short-term rentals — in lifecycle order",
 "blurb": "Buy, launch and run short-term rentals, in lifecycle order. Built from the Escape Velocity call archive — every lesson links to the recording it came from.",
 "moduleCount": 8,
 "lessonCount": 96,
 "sourceCalls": 21,
 "modules": [
  {
   "n": "0",
   "title": "Thesis — why Airbnb, and the velocity of money",
   "count": 12,
   "lessons": [
    {
     "title": "Equity is 10x more valuable than cash flow",
     "teaches": "Members learn to prioritize equity building over immediate cash flow when evaluating deals.",
     "rule": "The equity is like 10 times more valuable than the cash flow.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 965.5,
      "endSec": 1011.7,
      "at": "0:16:05",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=965",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/00-ev-call-1-sep-10-2025-velocity-of-money-965-ab8ijiU3DrFahmCdMufMFTtWiEDqZl.mp4",
       "dur": 150,
       "bytes": 13752928
      }
     },
     "alsoIn": []
    },
    {
     "title": "Prioritise tax and lifestyle over equity when you're a high-income W-2 earner",
     "teaches": "How to choose your investment priority based on your personal situation, so you optimise the lever that actually moves your net worth.",
     "rule": "If you're a high-income W-2 earner with kids who wants to quit your job, tax benefits should be your biggest priority because your biggest lever is tax, not time. If you're broke, cash flow is your number one priority. If you prioritise lifestyle, you may sacrifice some equity (e.g. buying turnkey instead of a 7-month renovation).",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 940.9,
      "endSec": 982.9,
      "at": "0:15:40",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=940",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-ev-call-29-mar-25-2026-market-selection-940-uamOYvGM1cTeFHR8zsqKL0cAGWvMdV.mp4",
       "dur": 150,
       "bytes": 9545877
      }
     },
     "alsoIn": []
    },
    {
     "title": "STR is the vehicle to run while you still have a W2",
     "teaches": "Why short-term rentals beat other investment vehicles for someone still employed full-time.",
     "rule": "There's not another option for an investment vehicle while you still have your W2 job, because STR is the only thing that will give you the tax savings. Invest in it heavily until you're out of your job.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 Office Hours 13 - Dec 2 2025 - John Bianchi Airbnb Data (guest)",
      "guest": "John Bianchi",
      "driveId": "1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU",
      "startSec": 2835.5,
      "endSec": 2876.7,
      "at": "0:47:15",
      "watch": "https://drive.google.com/file/d/1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU/view?t=2835",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-office-hours-13-dec-2-2025-john-bianchi-airbnb-data-guest-2835-FicmtK6jpGR3NWW3dbFrtmK7BAMgSi.mp4",
       "dur": 150,
       "bytes": 5598879
      }
     },
     "alsoIn": []
    },
    {
     "title": "Airbnb is not dead: focus on unique stays or family compounds",
     "teaches": "Members learn which types of short-term rentals will survive and thrive, so they can position their investments accordingly.",
     "rule": "The two types of Airbnbs that will live on are unique stays (e.g., potato, treehouses) and family compound style properties that sleep 15-20+ people with amenities like putt-putt and outdoor movie theaters.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 1262.4,
      "endSec": 1305.9,
      "at": "0:21:02",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=1262",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/00-ev-call-1-sep-10-2025-velocity-of-money-1262-vlsFEMxKJ8Fiugmt8xWYv49UaxYckk.mp4",
       "dur": 150,
       "bytes": 14662935
      }
     },
     "alsoIn": []
    },
    {
     "title": "The core STR model: short stays, high occupancy, above-market ADR",
     "teaches": "The baseline operating model for a short-term rental that makes the numbers work.",
     "rule": "Target two-night to three-night stays, 70% occupancy, and an average daily rate above the market average.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 2 - Sep 17 2025 - Velocity of Money and Trading Up",
      "guest": null,
      "driveId": "1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb",
      "startSec": 5953.0,
      "endSec": 5995.5,
      "at": "1:39:13",
      "watch": "https://drive.google.com/file/d/1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb/view?t=5953",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/00-ev-call-2-sep-17-2025-velocity-of-money-and-trading-up-5953-MG10BJ3o6MxqwUm5XFzQZmoVPskCEt.mp4",
       "dur": 150,
       "bytes": 1830910
      }
     },
     "alsoIn": []
    },
    {
     "title": "Forced appreciation plus leverage is how you build wealth",
     "teaches": "The member sees the math of how a small down payment plus renovations creates large equity gains.",
     "rule": "Leverage plus forced appreciation creates wealth. Example: $10k down on a $100k property, $10k in renovations, property worth $160k, so $60k of equity goes into your pocket.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "IRR vs ROI: why speed of money matters",
     "teaches": "Members learn the difference between ROI (total return) and IRR (annualized speed of return), and why the same multiple is worth more if you get it back faster.",
     "rule": "ROI is total cash returned divided by cash invested; IRR is the annualized compound rate of growth. The standard benchmark for a deal is a 15% IRR. A 100% IRR means you get all your money back in one year.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 991.0,
      "endSec": 1040.1,
      "at": "0:16:31",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=991",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-991-A9q7TkvYZLkqiX17DXRDvPPYhleG89.mp4",
       "dur": 150,
       "bytes": 9382528
      }
     },
     "alsoIn": []
    },
    {
     "title": "Cash on cash is the simple payback metric",
     "teaches": "Members get a quick mental shortcut: cash on cash tells you how many years to get your initial investment back.",
     "rule": "Cash on cash is an annual metric. A 10% cash on cash means it takes 10 years to get your initial investment back.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 1114.4,
      "endSec": 1161.8,
      "at": "0:18:34",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=1114",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-1114-0aMx7NBHciCTzBeNDUry9NYblSecIM.mp4",
       "dur": 150,
       "bytes": 9669745
      }
     },
     "alsoIn": []
    },
    {
     "title": "Shorten your hold period to double your IRR",
     "teaches": "Members see how cutting the hold period while keeping the same multiple dramatically increases IRR, so velocity of money beats a long slow hold.",
     "rule": "If you triple your money over 10 years that's roughly a 10 IRR; triple it in half the time (5 years) and the IRR doubles to about 20. Cutting the hold period in half turns a 3x into roughly a 2.5x but still doubles the IRR.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 1237.2,
      "endSec": 1285.8,
      "at": "0:20:37",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=1237",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-1237-nnhdQfSg7o9wPZlQrVLObVldZYTmJ5.mp4",
       "dur": 150,
       "bytes": 10176542
      }
     },
     "alsoIn": []
    },
    {
     "title": "Early years drag IRR down before cash flow catches up",
     "teaches": "Members understand why the first few years of an STR show negative or low IRR and why the back half of a hold is mostly cash flow that adds little velocity.",
     "rule": "In the first ~4 years you carry renovation, operations, startup and supply costs, so IRR can be negative (e.g. -100%) and only climbs slowly as cash flow builds. The last five years of a 10-year hold are mostly cash flow and don't add much to the velocity of money.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 1321.4,
      "endSec": 1368.0,
      "at": "0:22:01",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=1321",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-1321-0hVKUrYW6qNJQ9vtGUfanpMAHhc8XQ.mp4",
       "dur": 150,
       "bytes": 9328378
      }
     },
     "alsoIn": []
    },
    {
     "title": "Downtown Portland's collapse shows why appraised values lie",
     "teaches": "A real-world example of how pro forma and appraised values can evaporate, reinforcing the case for controllable assets.",
     "rule": "Downtown Portland real estate was valued at $3B pre-COVID and is now $990M — a third of its value. Pro formas and appraised values can collapse; leveraged office owners will lose everything.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 5209.3,
      "endSec": 5259.1,
      "at": "1:26:49",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=5209",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-5209-oCVYTRL28IyTVieRgO2XEK4Ph6R0cg.mp4",
       "dur": 150,
       "bytes": 8842373
      }
     },
     "alsoIn": []
    },
    {
     "title": "Invest for equity, not just cash flow",
     "teaches": "Why equity multiple matters and how forced appreciation separates good Airbnb investments from bad ones.",
     "rule": "Invest for equity. If you pour $300,000 into a property but the value only goes up $150,000, you destroyed value even if it cash flows. Track equity multiple so you know you're creating additional value, not just cash flow.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": 921.5,
      "endSec": 963.4,
      "at": "0:15:21",
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view?t=921",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-49-aug-26-2026-three-20-percent-rules-921-KVFNafReKAkkHbhACHb9Ysz6LbtVW6.mp4",
       "dur": 150,
       "bytes": 3493122
      }
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "1",
   "title": "Pick your market and your wedge",
   "count": 12,
   "lessons": [
    {
     "title": "Get under contract on a property within 30 days",
     "teaches": "Members are pushed to take immediate action toward acquiring their first or next short-term rental.",
     "rule": "In the next 30 days, you're going to be under contract on something.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 1997.7,
      "endSec": 2040.2,
      "at": "0:33:17",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=1997",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/00-ev-call-1-sep-10-2025-velocity-of-money-1997-oBc6sA3FFDuHP5703w6H8gITBLXK25.mp4",
       "dur": 150,
       "bytes": 13277384
      }
     },
     "alsoIn": []
    },
    {
     "title": "Look at 20-40 properties before you buy one",
     "teaches": "The volume of on-the-ground touring it takes to find the one property that actually meets your criteria.",
     "rule": "In Cleveland, Erin looked at at least 20-25 properties on her own and the one they bought was the only one that met their criteria. In Tucson they looked at roughly 40 properties over three days. Block out the whole day with your realtor and drive the neighborhoods.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "The 20% rule for revenue to purchase price",
     "teaches": "A quick screen to check whether a market and price point can support your revenue target before you go deeper.",
     "rule": "20% of the purchase price needs to be gross revenue. A $750,000 house needs to produce $150,000 in gross revenue. Look for properties in that market already making $150,000 or more and study what they're doing.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 1750.8,
      "endSec": 1793.0,
      "at": "0:29:10",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=1750",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-ev-call-29-mar-25-2026-market-selection-1750-sID3AjHNvB1xYxnJ08wcQgNLCxWPPt.mp4",
       "dur": 150,
       "bytes": 7664496
      }
     },
     "alsoIn": []
    },
    {
     "title": "The 20% revenue rule",
     "teaches": "The napkin-math screen that tells you whether a property's short-term rental revenue justifies the purchase price.",
     "rule": "Revenue must be at least 20% of purchase price. A $500,000 property needs to bring in $100,000 in revenue.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call - Sep 15 2026 - 30-Day Year-End Playbook",
      "guest": null,
      "driveId": "1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH",
      "startSec": 635.1,
      "endSec": 680.1,
      "at": "0:10:35",
      "watch": "https://drive.google.com/file/d/1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH/view?t=635",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-sep-15-2026-30-day-year-end-playbook-635-HloqRL8tYRcn6Id3DbfWdsVgEbz004.mp4",
       "dur": 150,
       "bytes": 7477220
      }
     },
     "alsoIn": []
    },
    {
     "title": "Avoid common property sizes like 3 bed 2 bath",
     "teaches": "Three-bed, two-bath homes are a very common size and may face more competition; consider unique configurations like two-bed, two-bath luxury homes for couples.",
     "rule": "Avoid buying 3 bed 2 bath homes because they are a really common size; instead, target unique configurations like 2 bed 2 bath luxury homes.",
     "speaker": "Zoey Berghoff",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": 4660.4,
      "endSec": 4698.1,
      "at": "1:17:40",
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view?t=4660",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-20-jan-28-2026-land-hacking-guest-zoey-berghoff-4660-V0nfW7Yc96MCfdFYHVE3RGa7VUJh7m.mp4",
       "dur": 150,
       "bytes": 10225067
      }
     },
     "alsoIn": []
    },
    {
     "title": "Permit caps create high-margin STR markets",
     "teaches": "The member learns to look for markets with permit caps and high visitor demand as a signal of strong STR performance.",
     "rule": "Look for markets with a limited number of permits and high visitor demand. Example: Orcas Island has only 230 permits and is not issuing more, creating a high-dollar, high-value, high-margin market.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Thin data can signal an underserved market",
     "teaches": "How to read a market with few listings as an opportunity rather than a red flag.",
     "rule": "When a market like Reno has very few listings for a five-guest search across the next six months, it means people with money want to go there but don't see what they want, so they book a hotel instead. The data doesn't support what's actually possible — no competition means you might do $130k.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Invest where the state protects homeowners",
     "teaches": "Why state-level regulation is a market selection criterion, not an afterthought.",
     "rule": "Arizona passed legislation protecting homeowners from cities and municipalities telling you what you can do with your property, so you can keep scaling in Tucson, Scottsdale and Yuma without worrying. Sacramento caps you at 180 days a year unless owner-occupied, which kills the deal if you can't be owner-occupied.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Heavily regulated markets are a moat if you'll jump the hoops",
     "teaches": "How permit requirements and caps can work in your favor by keeping competition out.",
     "rule": "In heavily regulated markets like San Diego, permits are capped at 1,000 listings and most people won't go through the hoops to get one. If you can jump through the hoops, you get a leg up because demand is there and supply is capped. But if demand isn't there — like Sacramento — the regulation is just a red flag.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Run the Airbnb market research filter method",
     "teaches": "A repeatable way to find the distinguishing amenities in a market by filtering Airbnb search results.",
     "rule": "On Airbnb, search the market with flexible weekend dates, set guests to two, then filter by amenities one at a time; if a filter like hot tub cuts over a thousand listings down to 121, that amenity is required.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Use the hot tub filter to prove an amenity is mandatory",
     "teaches": "How to read the Airbnb filter counts to decide which amenity you must add.",
     "rule": "In Phoenix, over a thousand listings host two guests; adding the hot tub filter drops it to 121, meaning over 90% of listings disappear, so you 100% need a hot tub.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Stack filters to find your real competition",
     "teaches": "How combining amenity filters reveals how few direct competitors you actually have.",
     "rule": "If you allow pets and have a hot tub, you're only competing against 62 other listings in the entire Phoenix metro area.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "2",
   "title": "Underwrite before you tour",
   "count": 12,
   "lessons": [
    {
     "title": "Avoid the dangerous $2M price point",
     "teaches": "Why a mid-tier price point traps you in 'what can we afford' thinking instead of buying a property that performs.",
     "rule": "The $2M price point is dangerous unless there is huge upside — it forces you into affordability-driven decisions rather than value-driven ones.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": 855.0,
      "endSec": 897.0,
      "at": "0:14:15",
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view?t=855",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-14-dec-8-2025-tax-leverage-hierarchy-855-gbnWrhXrmCAzgRioNqV3jPw6w7cDVT.mp4",
       "dur": 150,
       "bytes": 9519779
      }
     },
     "alsoIn": []
    },
    {
     "title": "The 2.5x equity multiple",
     "teaches": "What the equity multiple means and how to calculate it so you can screen a deal in one number.",
     "rule": "Equity multiple is not a multiple of purchase price. It is your total return (forced appreciation plus cash flow over five years; some people add tax benefits, Kassidy does not) divided by the cash you put in (down payment, furnishing, renovations). Target 2.5x or more. Example: $100K all-in cash must return $250K.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Cash on cash minimum of 15%",
     "teaches": "How to read cash on cash and the minimum threshold to accept, plus when you can bend it.",
     "rule": "Cash on cash is annual cash flow divided by your all-in cash in. 50% cash on cash pays back your investment in two years; 30% pays back in three years; 33% cash on cash on $100K in means $33K a year. Minimum cash on cash is 15%, unless you're forcing massive appreciation — then cash on cash can suffer. If you're not growing equity, it better be a cash flow monster.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "IRR is the speed metric — target 20%",
     "teaches": "What IRR measures and the target that ties your 2.5x to a five-year timeline.",
     "rule": "IRR (internal rate of return) is the velocity of money — how quickly you get your return. A 2.5x could happen over one, five or ten years; IRR tells you the speed. Target a 20% IRR, which means your 2.5x happens in about five years. The three underwriting targets are 2.5x equity multiple, 15% cash on cash minimum, and 20% IRR.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "The 20% rule screen",
     "teaches": "How to quickly test whether a property's revenue justifies its price before going further.",
     "rule": "The 20% rule: the property must generate 20% of the purchase price in annual revenue. A $300,000 property needs $60,000/year in revenue.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 391.5,
      "endSec": 441.5,
      "at": "0:06:31",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=391",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-391-mROICPkuN1F42OpreJWCVTai8oWmvr.mp4",
       "dur": 150,
       "bytes": 7632126
      }
     },
     "alsoIn": []
    },
    {
     "title": "Sensitivity analysis for 2.5x return",
     "teaches": "How to use sensitivity analysis to find the ADR and occupancy needed to hit a target return.",
     "rule": "If you're trying to get a 2.5x return, run a sensitivity analysis on ADR and occupancy to see what you need to hit your numbers.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": 6552.6,
      "endSec": 6601.2,
      "at": "1:49:12",
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view?t=6552",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-23-feb-18-2026-velocity-scorecard-6552-DePup08eE4cLF8b1PLhB8Nlo0pxEGb.mp4",
       "dur": 150,
       "bytes": 5836097
      }
     },
     "alsoIn": []
    },
    {
     "title": "The OG 20% rule: screen deals on projected top-line revenue",
     "teaches": "How to quickly screen whether an Airbnb candidate is worth pursuing using the original 20% rule from John Bianchi.",
     "rule": "When looking at a potential Airbnb, the projected top-line revenue should be roughly 20% of the purchase price. Use it as quick math to filter deals before going deeper.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": 368.1,
      "endSec": 412.8,
      "at": "0:06:08",
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view?t=368",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-49-aug-26-2026-three-20-percent-rules-368-3PHyItUeSZ5CTUlAfWoB33wVGEI6Zv.mp4",
       "dur": 150,
       "bytes": 4433353
      }
     },
     "alsoIn": []
    },
    {
     "title": "The second 20% rule: 20% cash-on-cash return",
     "teaches": "The cash-on-cash return threshold to hold a deal to when underwriting an Airbnb.",
     "rule": "Target a 20% cash-on-cash return. If your projected cash-on-cash is lower than 20%, the deal doesn't clear the bar.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": 523.5,
      "endSec": 568.3,
      "at": "0:08:43",
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view?t=523",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-49-aug-26-2026-three-20-percent-rules-523-IxSo8ucfXrYPYUBSbb78ASgId239yg.mp4",
       "dur": 150,
       "bytes": 4118410
      }
     },
     "alsoIn": []
    },
    {
     "title": "The third 20% rule: 20% IRR",
     "teaches": "How to use IRR as the third 20% screen so you're not just chasing cash flow.",
     "rule": "Aim for a 20% IRR. If you double your money in a year that's great, but the floor is 20% IRR on the investment.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": 673.5,
      "endSec": 715.5,
      "at": "0:11:13",
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view?t=673",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-49-aug-26-2026-three-20-percent-rules-673-DgaOxKi8Hmit33QXwzRMPnuYMzajGg.mp4",
       "dur": 150,
       "bytes": 4089761
      }
     },
     "alsoIn": []
    },
    {
     "title": "Pick two metrics: the OG 20% rule and equity multiple",
     "teaches": "Which two underwriting metrics to anchor on if you only track a couple.",
     "rule": "If you had to pick two metrics, pick the OG 20% rule (initial screen) and equity multiple. Make sure you're near 20% top-line revenue and that over time you more than double your money (2.5x equity multiple).",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": 891.7,
      "endSec": 936.6,
      "at": "0:14:51",
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view?t=891",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-49-aug-26-2026-three-20-percent-rules-891-XgFjdqZ3VWwiBVcvCsMQRft7uB2EHR.mp4",
       "dur": 150,
       "bytes": 3452154
      }
     },
     "alsoIn": []
    },
    {
     "title": "The $100K revenue rule on a ~$550K purchase",
     "teaches": "The revenue screen Kassidy applies to a purchase price before believing a deal works.",
     "rule": "On a property listed at $565K (likely closing near $530K), you want to be hitting $100K in revenue to justify that price. Check whether you can actually generate $100K on that property — comps in the area at $300-400 a night, booked out for the summer, support it. Two-bedroom properties in Tucson do $100K+.",
     "speaker": "Kassidy",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": 6223.4,
      "endSec": 6266.5,
      "at": "1:43:43",
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view?t=6223",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/04-ev-call-30-apr-1-2026-design-for-vibe-and-roi-erin-6223-SbD9tRlcXZrmefb59olMlQ1bS5ezwl.mp4",
       "dur": 150,
       "bytes": 7045430
      }
     },
     "alsoIn": []
    },
    {
     "title": "Use a 9 cap to back into value and renovation budget",
     "teaches": "How to underwrite an STR acquisition by dividing NOI by a cap rate to find value, then testing what renovation spend creates.",
     "rule": "Divide NOI by the cap rate to get value. At a 9 cap, a property doing 252 NOI is worth about 2.8M. If you can push gross revenue to 850 and spend 500K on renovation, the property is worth 3.7M — so the 500K spend creates the equity.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": 1208.7,
      "endSec": 1255.7,
      "at": "0:20:08",
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view?t=1208",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/06-ev-call-34-apr-22-2026-the-permit-game-1208-JnXZJvAWjol0nQO1lTMe8MYSSOquol.mp4",
       "dur": 150,
       "bytes": 6604574
      }
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "3",
   "title": "Structure and finance the purchase",
   "count": 12,
   "lessons": [
    {
     "title": "Use the 401k for proof of funds on a down payment",
     "teaches": "The member learns a practical workaround when they don't have cash in their checking account for a down payment.",
     "rule": "If you don't have the cash in your account for a down payment, you can show your 401k account as proof of funds if it has enough to cover the down payment.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Avoid PMI by putting 20% down",
     "teaches": "The tradeoff between putting less down and paying PMI, and when it makes sense to put more down.",
     "rule": "If you put under 20% down on a vacation/second home loan, you must pay PMI, which can be quoted very high. Sometimes putting an extra 10% down to avoid PMI is the better tradeoff.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "A 10-year loan kills cash flow and tax benefits",
     "teaches": "Short amortization raises your mortgage, lowers cash flow, and removes depreciation tax benefits, so it may not fit your buy box.",
     "rule": "A 10-year loan means a substantially higher mortgage, lower cash flow, and no tax benefits — it doesn't fit the standard buy box.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 4502.3,
      "endSec": 4546.6,
      "at": "1:15:02",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=4502",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-ev-call-29-mar-25-2026-market-selection-4502-wg5R8m6hRK0foc8sFFVPRWcUmIoEwm.mp4",
       "dur": 150,
       "bytes": 7659609
      }
     },
     "alsoIn": []
    },
    {
     "title": "Lender LTV and the 35% cash gap",
     "teaches": "How to calculate the cash needed when a lender provides 65% LTV.",
     "rule": "Lenders typically give 65% loan-to-value, so you need 35% of the purchase price in cash plus renovation costs.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": 5998.0,
      "endSec": 6042.4,
      "at": "1:39:58",
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view?t=5998",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-23-feb-18-2026-velocity-scorecard-5998-mrMvqdVgKBWextMuHmYuvDGuy5VrCt.mp4",
       "dur": 150,
       "bytes": 9254679
      }
     },
     "alsoIn": []
    },
    {
     "title": "Ask investors for the max that still hits a 10% cash-on-cash return",
     "teaches": "How to size the capital ask for a short-term rental project while protecting investor returns.",
     "rule": "Ask investors for the maximum amount that still allows them to receive a 10% cash-on-cash return in a worst-case scenario, then use that capital for design and amenities.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": 1383.7,
      "endSec": 1430.3,
      "at": "0:23:03",
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view?t=1383",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/03-ev-call-19-jan-21-2026-raising-money-for-strs-guest-sarah-1383-7yrhX9BliqBseaeJIyyzTPZbxQvQ9G.mp4",
       "dur": 150,
       "bytes": 8865974
      }
     },
     "alsoIn": []
    },
    {
     "title": "Dome house deal: 3.6x equity multiple with only 82k cash in",
     "teaches": "A concrete example of using hard money and a refinance to create a large equity multiple with minimal cash.",
     "rule": "Buy at 625k, put 10% down (~7.5-8k) on a hard money renovation loan, total project cost 800k, ARV 1.1M; bring only 82k cash, create 300k equity, and forecast 150-200k gross revenue (75-110k cash flow).",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 33 - Apr 14 2026 - Infinite Return BRRRR (guest Raj Chida)",
      "guest": "Raj Chida",
      "driveId": "16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB",
      "startSec": 803.1,
      "endSec": 847.1,
      "at": "0:13:23",
      "watch": "https://drive.google.com/file/d/16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB/view?t=803",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/03-ev-call-33-apr-14-2026-infinite-return-brrrr-guest-raj-ch-803-VWTPNfuBwlwqxdC1HrZb8GTndIhsm6.mp4",
       "dur": 150,
       "bytes": 3728765
      }
     },
     "alsoIn": []
    },
    {
     "title": "Put renovations on 0% APR cards — but only if you have the cash",
     "teaches": "Paying cash for renovations ties up your liquidity and can halt a project when an emergency hits. Using 0% cards preserves cash reserves.",
     "rule": "Never put a renovation on a 0% APR credit card unless you have the cash to cover it. Don't pay for renovations in cash — use 0% interest cards or points cards so you keep cash for emergencies like a $5,000 collapsed pipe.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": 3114.3,
      "endSec": 3159.3,
      "at": "0:51:54",
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view?t=3114",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-20-jan-28-2026-land-hacking-guest-zoey-berghoff-3114-VwWIwMXDVx4iXgsR84b3jl09J5pE6m.mp4",
       "dur": 150,
       "bytes": 3227849
      }
     },
     "alsoIn": []
    },
    {
     "title": "Understand the payback period on 0% APR cards",
     "teaches": "How to use 0% APR credit cards like a HELOC for short-term funding.",
     "rule": "If you understand the appraised value after the project, you can be confident you'll pay off the 0% APR or HELOC before interest kicks in. Know the payback period.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": 3339.6,
      "endSec": 3382.9,
      "at": "0:55:39",
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view?t=3339",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-20-jan-28-2026-land-hacking-guest-zoey-berghoff-3339-IbB6wYWkpK141rcx6Y9apEkVkDcFxM.mp4",
       "dur": 150,
       "bytes": 3242183
      }
     },
     "alsoIn": []
    },
    {
     "title": "Leverage is how you buy high-priced assets for a fraction of the price",
     "teaches": "The member learns to evaluate leverage by comparing down payment percentages and opportunity cost, not just interest rate.",
     "rule": "Leverage is debt. Compare 10% down vs 40% down and look at the opportunity cost of your cash. Interest rate is just a line item on a spreadsheet that adds to the cost of debt.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Own equity without putting in your own money",
     "teaches": "How to accelerate ownership by structuring deals so you get equity without a cash down payment, and how to weigh the effort that requires.",
     "rule": "The ultimate form of leverage is owning a piece of an asset without putting your own money in. Weigh what it costs you in effort: raising money, managing construction, doing the work. Free equity is the ultimate leverage; buying outright is high leverage; investing as an LP is lower leverage (roughly 1 to 3 vs 1 to 5) and a higher cost of equity.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Use vacation rental loans for higher leverage",
     "teaches": "Why and when to use a vacation rental loan to put less down and keep cash reserves.",
     "rule": "If the property is 50+ miles from your home, you can use a vacation rental loan and put only 10% down instead of 20%, keeping more cash for reserves and emergencies.",
     "speaker": "Bobby",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Don't put more cash down just to improve cash flow",
     "teaches": "Why putting extra cash down to boost cash flow is often a poor use of capital.",
     "rule": "Putting an extra 5% down (e.g., $25k on a $500k purchase) to create an extra $5k of cash flow takes five years to get that money back. Instead, focus on growing revenue, optimizing renovations for impact, or changing your debt structure (e.g., seller financing).",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "4",
   "title": "Design and furnish for revenue",
   "count": 12,
   "lessons": [
    {
     "title": "Spend $3,000 on the backyard, not $50-60k",
     "teaches": "The right budget band for an outdoor amenity package in a market that doesn't demand a full build-out.",
     "rule": "Don't invest $50,000-$60,000 in the backyard — it won't be worth it. Throw $3,000 at it with a whack load of things people can do (chairs, seating, games) and you'll have something most others in the market don't have.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 Office Hours 13 - Dec 2 2025 - John Bianchi Airbnb Data (guest)",
      "guest": "John Bianchi",
      "driveId": "1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU",
      "startSec": 4157.8,
      "endSec": 4200.2,
      "at": "1:09:17",
      "watch": "https://drive.google.com/file/d/1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU/view?t=4157",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-office-hours-13-dec-2-2025-john-bianchi-airbnb-data-guest-4157-H14xFnq3hvIA8Ep3BJjfIlXNwRv77f.mp4",
       "dur": 150,
       "bytes": 6849138
      }
     },
     "alsoIn": []
    },
    {
     "title": "Buy sleeper sofas from Apt2B with the most durable fabric",
     "teaches": "A specific vendor and spec for a comfortable, durable sleeper sofa that guests will actually sleep on.",
     "rule": "Buy sleeper sofas from Apt2B, choose the most durable fabric, and upgrade to the nicer mattress option.",
     "speaker": "Erin",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": 2587.2,
      "endSec": 2636.3,
      "at": "0:43:07",
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view?t=2587",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/04-ev-call-30-apr-1-2026-design-for-vibe-and-roi-erin-2587-xTFZZGzCp4JmEjyOy6t9lfIaIAgG43.mp4",
       "dur": 150,
       "bytes": 3467204
      }
     },
     "alsoIn": []
    },
    {
     "title": "Update a dated kitchen for $5K, not $30K",
     "teaches": "How to make an old kitchen usable and thoughtful on a small budget instead of a full gut renovation.",
     "rule": "On an 1880s cabin kitchen, a full new kitchen wasn't possible, so the move was to update it for about $5,000 to make it usable and thoughtful with a little design, rather than spending $30,000. Draw the line on spend where the structure doesn't justify it — that cabin had no foundation, so a $100,000 renovation didn't make sense.",
     "speaker": "Kassidy",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": 5862.2,
      "endSec": 5912.2,
      "at": "1:37:42",
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view?t=5862",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/04-ev-call-30-apr-1-2026-design-for-vibe-and-roi-erin-5862-tKtiRhIahzjrumZFU3tdx97s4Hf6tA.mp4",
       "dur": 150,
       "bytes": 7593361
      }
     },
     "alsoIn": []
    },
    {
     "title": "Click-lock floating vinyl at 6mm minimum",
     "teaches": "The flooring spec to use in an STR renovation.",
     "rule": "Click-lock floating vinyl is usually the preferred flooring. Use at least a 6 millimeter thickness.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": 2176.8,
      "endSec": 2222.4,
      "at": "0:36:16",
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view?t=2176",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/06-ev-call-34-apr-22-2026-the-permit-game-2176-RyJHCvCbDUsptAdkaku5OVbQBQF6cr.mp4",
       "dur": 150,
       "bytes": 5855800
      }
     },
     "alsoIn": []
    },
    {
     "title": "Add a jacuzzi to lift revenue and pay it back fast",
     "teaches": "A specific amenity upgrade that raises nightly revenue and pays for itself quickly on a small STR.",
     "rule": "A brand-new jacuzzi costs about $5K and pays for itself in under a year through higher revenue. Add the jacuzzi first, then layer on a cold plunge and sauna as you go.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Add a hot tub and sauna to boost revenue fast",
     "teaches": "How to use high-ROI amenities like a hot tub and sauna to increase bookings and revenue, with specific cost and payback numbers.",
     "rule": "A brand-new $5k hot tub can pay for itself in under a year; budget roughly $20k for the hot tub, $15k for a sauna, and $10k for labor/setup. Buy a nicer smaller sauna (e.g., SaunaLife ~$5k) rather than a cheap one.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Build an optimization list with a dollar figure",
     "teaches": "How to budget the design/furnish spend as a defined line item tied to a revenue target.",
     "rule": "Write an optimization list: 'I'm going to have to spend $100,000 to optimize this listing and then it will hit the revenue numbers I'm trying to hit.'",
     "speaker": "Kassidy",
     "source": {
      "label": "01 Office Hours 13 - Dec 2 2025 - John Bianchi Airbnb Data (guest)",
      "guest": "John Bianchi",
      "driveId": "1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU",
      "startSec": 2660.9,
      "endSec": 2702.5,
      "at": "0:44:20",
      "watch": "https://drive.google.com/file/d/1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU/view?t=2660",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-office-hours-13-dec-2-2025-john-bianchi-airbnb-data-guest-2660-G4WnRMSSbM7lUthujLNuBA3b1ntpyD.mp4",
       "dur": 150,
       "bytes": 7060002
      }
     },
     "alsoIn": []
    },
    {
     "title": "Wellness amenities can drive outsized revenue",
     "teaches": "How to use wellness amenities to differentiate your STR and justify higher revenue.",
     "rule": "Install saunas, cold plunges, hot tubs, red light therapy, and theragun in your BnB to serve a wellness-focused avatar; budget around $3k for a sauna and $3k for a cold plunge, and spend more on hot tubs (e.g., Master Spas) for reliability.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": 1184.7,
      "endSec": 1229.7,
      "at": "0:19:44",
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view?t=1184",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/03-ev-call-19-jan-21-2026-raising-money-for-strs-guest-sarah-1184-1HbDkGWDL5J6nrSB9QMbvWw70EwRsq.mp4",
       "dur": 150,
       "bytes": 9710907
      }
     },
     "alsoIn": []
    },
    {
     "title": "Build a headboard shelf for a small bedroom",
     "teaches": "A simple design upgrade to make a small bedroom more functional and appealing.",
     "rule": "Build a headboard that spans the wall as a 6-8 inch shelf with a built-in cubby for laptops or decor.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 33 - Apr 14 2026 - Infinite Return BRRRR (guest Raj Chida)",
      "guest": "Raj Chida",
      "driveId": "16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB",
      "startSec": 84.8,
      "endSec": 134.1,
      "at": "0:01:24",
      "watch": "https://drive.google.com/file/d/16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB/view?t=84",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/03-ev-call-33-apr-14-2026-infinite-return-brrrr-guest-raj-ch-84-H9xziVIdvBhjYRAXNcal9KO2J5n9Uj.mp4",
       "dur": 150,
       "bytes": 10403135
      }
     },
     "alsoIn": []
    },
    {
     "title": "Source doors and windows from salvage yards",
     "teaches": "A budget hack for getting character pieces like solid wood doors at a fraction of retail cost.",
     "rule": "Buy doors and windows from a salvage/resale yard. A gorgeous solid wood door can cost about $50; a full door swap installed runs roughly $250-$300.",
     "speaker": "Kassidy",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": 1598.5,
      "endSec": 1648.3,
      "at": "0:26:38",
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view?t=1598",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/04-ev-call-30-apr-1-2026-design-for-vibe-and-roi-erin-1598-ZwXJQ3mp07nPLxv8Rrvn798kqlGmiA.mp4",
       "dur": 150,
       "bytes": 3895750
      }
     },
     "alsoIn": []
    },
    {
     "title": "Renovation spend can double your equity and cashflow",
     "teaches": "How a well-executed renovation and furnishing package can create immediate equity and strong cashflow.",
     "rule": "On a $460k property, spending $80k on renovation and furnishings created about $90k of equity and a mortgage under $2k/month, with annual operating costs around $30k.",
     "speaker": "Erin",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": 2195.9,
      "endSec": 2240.5,
      "at": "0:36:35",
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view?t=2195",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/04-ev-call-30-apr-1-2026-design-for-vibe-and-roi-erin-2195-lpWbodEARHGPVfs7GDQ9BKTy6rj5j7.mp4",
       "dur": 150,
       "bytes": 3523575
      }
     },
     "alsoIn": []
    },
    {
     "title": "Add indoor-outdoor access for warm-climate Airbnbs",
     "teaches": "A high-ROI renovation move for vacation rentals in warm climates: replace a small window with a large slider to the pool/patio.",
     "rule": "In a warm climate, guests want indoor-outdoor access. Replacing a tiny window with a three-panel slider to the pool completely changed the guest experience and adds resale value. Cost: about $5,000 for the door plus $3,500 for install, under $10,000 all-in including the steel lintel.",
     "speaker": "Kassidy",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": 3277.7,
      "endSec": 3324.2,
      "at": "0:54:37",
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view?t=3277",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/04-ev-call-30-apr-1-2026-design-for-vibe-and-roi-erin-3277-z6pKXTMBgvkzoh9Bdi3ADe7jdRmWPy.mp4",
       "dur": 150,
       "bytes": 3653884
      }
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "5",
   "title": "Launch and rank on Airbnb",
   "count": 12,
   "lessons": [
    {
     "title": "Airbnb shifted its host fee from 3% to ~16%",
     "teaches": "What changed in Airbnb's fee structure and how to respond as a host.",
     "rule": "As of this month Airbnb moved the fee from ~3% to ~16% onto the host; the guest-facing price looks the same, so hosts must raise prices to absorb it.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
      "guest": null,
      "driveId": "1IBSkQMG1pWkdqSBELz4drvHAOacHylmO",
      "startSec": 4782.0,
      "endSec": 4822.9,
      "at": "1:19:42",
      "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view?t=4782",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-8-oct-29-2025-adu-velocity-4782-PrwtSqht91T5mmrDEsycwLeYOMDlBw.mp4",
       "dur": 150,
       "bytes": 8462785
      }
     },
     "alsoIn": []
    },
    {
     "title": "Make your listing stupid obvious",
     "teaches": "How to make your listing stand out in search by clearly showing all amenities so guests instantly know what they get.",
     "rule": "Make everything on your Airbnb stupid obvious so when someone searches 20 listings, they know exactly what they're getting.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 Office Hours 13 - Dec 2 2025 - John Bianchi Airbnb Data (guest)",
      "guest": "John Bianchi",
      "driveId": "1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU",
      "startSec": 1478.4,
      "endSec": 1519.1,
      "at": "0:24:38",
      "watch": "https://drive.google.com/file/d/1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU/view?t=1478",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-office-hours-13-dec-2-2025-john-bianchi-airbnb-data-guest-1478-YJij2QnBsTpcsHXI3vTOGUgB3qCg4u.mp4",
       "dur": 150,
       "bytes": 4748758
      }
     },
     "alsoIn": []
    },
    {
     "title": "Hot tubs boost search ranking in low-supply markets",
     "teaches": "How to use a high-demand amenity to climb Airbnb search rankings even when your photos are weak.",
     "rule": "Check what share of listings in your market have a hot tub. If only ~10% do, adding one can push you into the top results even with a bad hero photo.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 EV Call 9 - Nov 5 2025 - Listing Optimization",
      "guest": null,
      "driveId": "1xI3nQLC2thLMvWxRCpyKTSlwfe3Dov9E",
      "startSec": 2291.3,
      "endSec": 2332.3,
      "at": "0:38:11",
      "watch": "https://drive.google.com/file/d/1xI3nQLC2thLMvWxRCpyKTSlwfe3Dov9E/view?t=2291",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/05-ev-call-9-nov-5-2025-listing-optimization-2291-OT5WAVe5BlR2mWlgY9erFW9RKQIePz.mp4",
       "dur": 150,
       "bytes": 5570431
      }
     },
     "alsoIn": []
    },
    {
     "title": "Set an eight-week lead time and a go-live deadline",
     "teaches": "Why you need a hard launch date and how far ahead to plan it.",
     "rule": "Set a deadline for yourself with an eight-week lead time, and aim to go live by June 15th at the latest so you capture the July 4th booking — going live July 3rd means you only get last-minute or cancelled-guest bookings.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": 4382.6,
      "endSec": 4423.9,
      "at": "1:13:02",
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view?t=4382",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/06-ev-call-34-apr-22-2026-the-permit-game-4382-uJbBU7dcO1OzZwUHlupQz84V0fi6CC.mp4",
       "dur": 150,
       "bytes": 7313568
      }
     },
     "alsoIn": []
    },
    {
     "title": "Child-parent listings to hit the search algorithm",
     "teaches": "How to create multiple Airbnb listings from a single purchase to widen your search reach.",
     "rule": "Create a child-parent listing relationship: one listing for the entire property, one for the main house, one for the guest house. One purchase = three Airbnb listings, letting you accommodate 2, 7, or 11 people and hit the search algorithm more favorably.",
     "speaker": "Zoey Berghoff",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": 872.5,
      "endSec": 919.8,
      "at": "0:14:32",
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view?t=872",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-20-jan-28-2026-land-hacking-guest-zoey-berghoff-872-2ogvhcUMWMMMEvuNtZ5b35JlJBfjcb.mp4",
       "dur": 150,
       "bytes": 2939776
      }
     },
     "alsoIn": []
    },
    {
     "title": "Direct booking can pay you more while guests pay less",
     "teaches": "The economics of direct bookings versus OTA channels.",
     "rule": "Direct bookings can save guests 5-10% depending on how your rates are set up, while you get paid out the same or more than through the OTA.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": 2166.3,
      "endSec": 2207.3,
      "at": "0:36:06",
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view?t=2166",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/05-office-hours-15-dec-18-2025-launch-and-feed-the-beast-2166-dJueOvywMKSAd5oGkiUj29SxaOf1tN.mp4",
       "dur": 150,
       "bytes": 7413251
      }
     },
     "alsoIn": []
    },
    {
     "title": "Screen guests by star rating",
     "teaches": "A guest-vetting rule to reduce problem bookings.",
     "rule": "Look at a guest's profile and prefer guests with a 4.5 star rating or above.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 42 - Jul 1 2026 - Every Issue Becomes an SOP (Erin)",
      "guest": null,
      "driveId": "1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z",
      "startSec": 3290.0,
      "endSec": 3332.3,
      "at": "0:54:50",
      "watch": "https://drive.google.com/file/d/1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z/view?t=3290",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/06-ev-call-42-jul-1-2026-every-issue-becomes-an-sop-erin-3290-mfMRBehEN3UrrArDkLUFq8mlnK5ouY.mp4",
       "dur": 150,
       "bytes": 8490905
      }
     },
     "alsoIn": []
    },
    {
     "title": "Use Airbnb direct booking links with Hospitable",
     "teaches": "Members learn how to use Airbnb's direct booking links and the cost tradeoff with Hospitable.",
     "rule": "Airbnb now has direct booking links; with Hospitable you pay 6% for background check and license upload. Keeping people on Airbnb is fine because they're familiar with it.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call - Sep 15 2026 - 30-Day Year-End Playbook",
      "guest": null,
      "driveId": "1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH",
      "startSec": 4394.4,
      "endSec": 4442.8,
      "at": "1:13:14",
      "watch": "https://drive.google.com/file/d/1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH/view?t=4394",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-sep-15-2026-30-day-year-end-playbook-4394-gEImuyXVYU7BRZx2jojGKazaa0QYF5.mp4",
       "dur": 150,
       "bytes": 7907376
      }
     },
     "alsoIn": []
    },
    {
     "title": "Use your unique selling points to fill all booking channels",
     "teaches": "Your unique selling points should be used consistently across all marketing channels and feeder markets to attract the right guests.",
     "rule": "Leverage your unique selling points across every channel and feeder market to fill your calendar.",
     "speaker": "Katie Cline",
     "source": {
      "label": "01 EV Call 43 - Jul 8 2026 - Positioning Workshop (guest Katie Cline)",
      "guest": "Katie Cline",
      "driveId": "1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI",
      "startSec": 1905.2,
      "endSec": 1949.5,
      "at": "0:31:45",
      "watch": "https://drive.google.com/file/d/1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI/view?t=1905",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-ev-call-43-jul-8-2026-positioning-workshop-guest-katie-cl-1905-T1F2250wleLAnTU3XlwSLCDuoJCxdL.mp4",
       "dur": 150,
       "bytes": 4012257
      }
     },
     "alsoIn": []
    },
    {
     "title": "Keep instant book on to capture more bookings",
     "teaches": "Instant book removes friction and captures guests who want to book immediately, increasing conversion.",
     "rule": "Turn instant book on; it's booking behavior and you can get multiple bookings.",
     "speaker": "Katie Cline",
     "source": {
      "label": "01 EV Call 43 - Jul 8 2026 - Positioning Workshop (guest Katie Cline)",
      "guest": "Katie Cline",
      "driveId": "1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI",
      "startSec": 4179.7,
      "endSec": 4221.1,
      "at": "1:09:39",
      "watch": "https://drive.google.com/file/d/1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI/view?t=4179",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-ev-call-43-jul-8-2026-positioning-workshop-guest-katie-cl-4179-v7yFK7ZLlvgxx2hpVuNy6t88PGgIIG.mp4",
       "dur": 150,
       "bytes": 3258838
      }
     },
     "alsoIn": []
    },
    {
     "title": "The best return on an Airbnb is a photo shoot",
     "teaches": "Where to put your first marketing dollars to lift desirability and nightly rate.",
     "rule": "The best return you will ever do into your Airbnb is getting a good photo shoot. Photos are what sell a listing — you're trying to get someone to give you money, so you have to sell them.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 Office Hours 13 - Dec 2 2025 - John Bianchi Airbnb Data (guest)",
      "guest": "John Bianchi",
      "driveId": "1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU",
      "startSec": 3251.2,
      "endSec": 3293.7,
      "at": "0:54:11",
      "watch": "https://drive.google.com/file/d/1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU/view?t=3251",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-office-hours-13-dec-2-2025-john-bianchi-airbnb-data-guest-3251-PzLFaAXIAi6LTw1nY9M47ADVfHyarb.mp4",
       "dur": 150,
       "bytes": 7335002
      }
     },
     "alsoIn": []
    },
    {
     "title": "The first five photos decide the click — order them deliberately",
     "teaches": "How to sequence listing photos so the best exterior features land in the first five.",
     "rule": "The first five photos matter most; show off everything outside that makes you better before touching the inside, and put the pool/outdoor space near the top, not the bottom.",
     "speaker": "John Bianchi",
     "source": {
      "label": "01 Office Hours 13 - Dec 2 2025 - John Bianchi Airbnb Data (guest)",
      "guest": "John Bianchi",
      "driveId": "1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU",
      "startSec": 5944.3,
      "endSec": 5986.6,
      "at": "1:39:04",
      "watch": "https://drive.google.com/file/d/1GeMcuAFDXLH0neg5fKInGtBp-9XrsjvU/view?t=5944",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-office-hours-13-dec-2-2025-john-bianchi-airbnb-data-guest-5944-PKIS5x5ZS3S7IZ9LLBjRE48J7yD7Q1.mp4",
       "dur": 150,
       "bytes": 12383932
      }
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "6",
   "title": "Run it like a micro hotel",
   "count": 12,
   "lessons": [
    {
     "title": "Maintain a high review score above 4.9",
     "teaches": "The importance of consistently high guest ratings for long-term success.",
     "rule": "Aim to keep your Airbnb review score above 4.9, even with amenities like pools and hot tubs, as it is difficult but valuable over many years.",
     "speaker": "Erin",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": 1087.7,
      "endSec": 1135.1,
      "at": "0:18:07",
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view?t=1087",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/04-ev-call-30-apr-1-2026-design-for-vibe-and-roi-erin-1087-2kdSrgbA5RhSABitxTX8cRNda2wjUb.mp4",
       "dur": 150,
       "bytes": 4225896
      }
     },
     "alsoIn": []
    },
    {
     "title": "Cap your guest count at 7 or 8 to avoid the party demographic",
     "teaches": "A simple rule to protect your property from excessive wear and tear and problematic guests.",
     "rule": "Never host more than 8 guests; 7 is a preferred maximum. Larger groups cause more damage and are harder on the property.",
     "speaker": "Zoey Berghoff",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": 4728.2,
      "endSec": 4769.4,
      "at": "1:18:48",
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view?t=4728",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-20-jan-28-2026-land-hacking-guest-zoey-berghoff-4728-kNMi2CvMUDPpIKpq8UBXiGlubxYh9S.mp4",
       "dur": 150,
       "bytes": 10351116
      }
     },
     "alsoIn": []
    },
    {
     "title": "Personal use of your STR is a cost of core memories",
     "teaches": "The member learns to account for personal use when evaluating an STR's annual revenue.",
     "rule": "If you use your STR during peak season, you lose revenue. Example: losing about $20k in summer, but that's the cost of creating core memories.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Keep cash flow in the property account as your reserve",
     "teaches": "How to handle cash flow and build an emergency fund for your STR.",
     "rule": "Keep all cash flow in the property account and only use it to pay bills, mortgage, and housekeepers. If you lack cash reserves, have space on credit cards, stocks, or other sources as backup; put large unexpected expenses like a $20k AC on a 0% interest credit card rather than paying cash.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Assume guests have good intentions when managing issues",
     "teaches": "Approach guest problems with the assumption that guests mean well, which reduces stress and leads to better resolutions.",
     "rule": "Assume everyone has good intentions; 99% of guests are there to have a great time.",
     "speaker": "Katie Cline",
     "source": {
      "label": "01 EV Call 43 - Jul 8 2026 - Positioning Workshop (guest Katie Cline)",
      "guest": "Katie Cline",
      "driveId": "1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI",
      "startSec": 4221.4,
      "endSec": 4242.7,
      "at": "1:10:21",
      "watch": "https://drive.google.com/file/d/1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI/view?t=4221",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/01-ev-call-43-jul-8-2026-positioning-workshop-guest-katie-cl-4221-1Ki3F146CkFxzDFEgf8mv4AW2w2aHQ.mp4",
       "dur": 150,
       "bytes": 3257848
      }
     },
     "alsoIn": []
    },
    {
     "title": "Three ways to handle food and beverage at your property",
     "teaches": "How to decide whether to partner, lease, or outsource the food component of a hospitality property.",
     "rule": "Option 1: partner with a chef/restaurateur who puts money in and collaborates on design (true partner, integrated). Option 2: lease the space to them at discounted rent plus a rev share (lower risk for them, you get rent plus upside). Option 3: outsource by partnering with existing restaurants for grab-and-go or high-end prepared packaged food — you outsource the labor.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 2175.4,
      "endSec": 2220.3,
      "at": "0:36:15",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=2175",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-2175-QqWXxsgaFbWmSMbxvFXhrCpDtRNXLz.mp4",
       "dur": 150,
       "bytes": 8242928
      }
     },
     "alsoIn": []
    },
    {
     "title": "Mid-term rentals can replace income with less work",
     "teaches": "How to use mid-term rentals to reduce workload while keeping income and depreciation benefits.",
     "rule": "If you hit 700 hours in real estate in a year you can qualify for REP status; then you can switch a property to mid- or long-term and make close to the same amount with way less work, while still taking depreciation on a mid-term.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": 6231.9,
      "endSec": 6280.9,
      "at": "1:43:51",
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view?t=6231",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/05-office-hours-15-dec-18-2025-launch-and-feed-the-beast-6231-dhDoRsom3n5DVISWiUvRGhgSCb1nOc.mp4",
       "dur": 150,
       "bytes": 6358469
      }
     },
     "alsoIn": []
    },
    {
     "title": "Delegate maintenance with a price cap",
     "teaches": "How to hand off repair coordination to your team without getting pulled back in.",
     "rule": "Give your VA/maintenance coordinator a price point (e.g. under $600) and let them handle the whole repair — sourcing, hauling, and guest follow-up — without you.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 42 - Jul 1 2026 - Every Issue Becomes an SOP (Erin)",
      "guest": null,
      "driveId": "1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z",
      "startSec": 1071.3,
      "endSec": 1112.1,
      "at": "0:17:51",
      "watch": "https://drive.google.com/file/d/1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z/view?t=1071",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/06-ev-call-42-jul-1-2026-every-issue-becomes-an-sop-erin-1071-JMWCSkOTiZeeCfG9aIoD4dHZcGOLV5.mp4",
       "dur": 150,
       "bytes": 9965429
      }
     },
     "alsoIn": []
    },
    {
     "title": "Refund the nightly rate, not the whole stay",
     "teaches": "How to compensate an unhappy guest without giving away the full booking.",
     "rule": "For a complaint, refund only the nightly rate (e.g. ~30%, about $300), not the entire stay.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 42 - Jul 1 2026 - Every Issue Becomes an SOP (Erin)",
      "guest": null,
      "driveId": "1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z",
      "startSec": 1475.1,
      "endSec": 1517.0,
      "at": "0:24:35",
      "watch": "https://drive.google.com/file/d/1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z/view?t=1475",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/06-ev-call-42-jul-1-2026-every-issue-becomes-an-sop-erin-1475-Qgo0UULs42MqyeIfyxWdeIaMePeH0E.mp4",
       "dur": 150,
       "bytes": 9337764
      }
     },
     "alsoIn": []
    },
    {
     "title": "Use a local gift card to smooth over complaints",
     "teaches": "A cheap gesture that often lands better than a cash refund with upset guests.",
     "rule": "Offer a $100 gift card to a favourite local spot (burger place, ice cream shop) — sometimes it matters more to the guest than a refund.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 42 - Jul 1 2026 - Every Issue Becomes an SOP (Erin)",
      "guest": null,
      "driveId": "1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z",
      "startSec": 1521.8,
      "endSec": 1563.2,
      "at": "0:25:21",
      "watch": "https://drive.google.com/file/d/1eoqmnboAMwYocMwEq4qIbb8E9aKxQT2z/view?t=1521",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/06-ev-call-42-jul-1-2026-every-issue-becomes-an-sop-erin-1521-eMjpv7X7wQYUQv4iCY0YEr1eTBMQT1.mp4",
       "dur": 150,
       "bytes": 9230718
      }
     },
     "alsoIn": []
    },
    {
     "title": "Small STRs can be cash cows with high occupancy",
     "teaches": "How a small two-bedroom cabin can generate high revenue and occupancy.",
     "rule": "A 1,000 sq ft two-bedroom, two-bath cabin can surpass $140,000 in revenue in year one and achieve 90-100% occupancy.",
     "speaker": "Zoey Berghoff",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": 2269.5,
      "endSec": 2313.0,
      "at": "0:37:49",
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view?t=2269",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-20-jan-28-2026-land-hacking-guest-zoey-berghoff-2269-YLwNJa87gIqeXSY2aNtOYMY2nAd2Uz.mp4",
       "dur": 150,
       "bytes": 3154913
      }
     },
     "alsoIn": []
    },
    {
     "title": "Manage an STR next to your own construction site",
     "teaches": "Options for what to do with an existing unit while you build the next structure.",
     "rule": "If you're building right next door to a rentable unit, either run it as a midterm or 6-month long-term rental, cross it off and live in it yourself (being a present owner saves money and lets you run errands for the contractor), or keep it as an STR and disclose the construction.",
     "speaker": "Zoey Berghoff",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": 4134.2,
      "endSec": 4179.2,
      "at": "1:08:54",
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view?t=4134",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/07-ev-call-20-jan-28-2026-land-hacking-guest-zoey-berghoff-4134-d3NZgSeZGdKbsPO2PrTAVNeVV2E2SV.mp4",
       "dur": 150,
       "bytes": 10261268
      }
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "7",
   "title": "Equity, ADUs and tax",
   "count": 12,
   "lessons": [
    {
     "title": "Estimate tax savings as 20-30% of purchase price",
     "teaches": "A quick conservative rule of thumb for how much tax write-off an STR purchase generates, so you can size the deal against your active income.",
     "rule": "Tax savings from a property are roughly 20-30% of the purchase price. On a $1M property, expect a $200K-$300K write-off, conservatively. Base it on your W2/active income to know how much you need to offset.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "endSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Use a 1031 exchange to defer taxes and depreciation recapture",
     "teaches": "Members learn that selling an Airbnb without a 1031 exchange triggers depreciation recapture taxed as ordinary income, and how a 1031 avoids it.",
     "rule": "When you sell, all depreciation taken is recaptured as ordinary income. Example: $400k depreciation on a $500k property could create a $120k tax bill at 32% even if you only net $100k cash. A 1031 exchange defers both capital gains and depreciation recapture.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3057.6,
      "endSec": 3106.6,
      "at": "0:50:57",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3057",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3057-nxDl0PP5vn2CrIM57P7IFbyYR0xisR.mp4",
       "dur": 150,
       "bytes": 8610664
      }
     },
     "alsoIn": []
    },
    {
     "title": "Meet the 45-day and 180-day 1031 deadlines",
     "teaches": "Members learn the strict timelines for a 1031 exchange and why residential-to-residential exchanges are harder than commercial.",
     "rule": "After closing the sale, you have 45 days to identify a replacement property and 180 days total to close. Residential sellers are often unwilling to wait, making commercial properties (like hotels) easier because they typically take 90 days to close and you control the timeline via the PSA.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3234.6,
      "endSec": 3282.3,
      "at": "0:53:54",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3234",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3234-BWdjRKGu5Ih8EWswVsWfSMDGvYUGIF.mp4",
       "dur": 150,
       "bytes": 10092018
      }
     },
     "alsoIn": []
    },
    {
     "title": "Trade up from residential to commercial with a 1031",
     "teaches": "Members learn the strategy of using a 1031 exchange to move from a residential Airbnb into a larger commercial property to boost value.",
     "rule": "Sell a residential rental and 1031 into a commercial property (e.g., hotel) where you can force appreciation and increase equity. This is how you 'trade up' in real estate.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3331.8,
      "endSec": 3375.1,
      "at": "0:55:31",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3331",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3331-3hwOMaFPpwUCNgDTStDBF526IEGC77.mp4",
       "dur": 150,
       "bytes": 9961415
      }
     },
     "alsoIn": []
    },
    {
     "title": "The Lazy 1031: Offset Depreciation Recapture Without the 45-Day Rule",
     "teaches": "How to avoid paying tax on depreciation recapture by buying another property in the same calendar year, even if you missed the formal 1031 exchange deadline.",
     "rule": "If you sell a property and have depreciation recapture (e.g., $400k), you can buy another investment property and put it in service before December 31st of the same year to offset that recapture. This is called the 'lazy 1031' and does not require the 45-day identification or 180-day closing rules of a formal 1031 exchange.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3400.1,
      "endSec": 3446.6,
      "at": "0:56:40",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3400",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3400-jGZusN3KNT9xAFTzICaa9MbFFm14UC.mp4",
       "dur": 150,
       "bytes": 10071801
      }
     },
     "alsoIn": []
    },
    {
     "title": "Lazy 1031 vs. Formal 1031: Efficiency and Tax Impact",
     "teaches": "Why a formal 1031 exchange is more tax-efficient than the lazy 1031, and how to calculate the difference.",
     "rule": "A formal 1031 exchange defers all capital gains and depreciation recapture, and the new property's depreciation can offset other income. With a lazy 1031, the new property's depreciation must first offset the depreciation recapture from the sold property, leaving less to offset other income. Example: $400k recapture + $500k other income = $900k total income. With 1031, the $400k disappears and $50",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3583.3,
      "endSec": 3629.5,
      "at": "0:59:43",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3583",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3583-5DJ1O5mOVMELfIAoMzMrgiNu3orEMU.mp4",
       "dur": 150,
       "bytes": 11785055
      }
     },
     "alsoIn": []
    },
    {
     "title": "Using 1031 to Acquire Land for Future Development",
     "teaches": "How to use a 1031 exchange to buy land, even though land is not depreciable, and potentially convert it to a primary residence later.",
     "rule": "You can 1031 exchange from a short-term rental or hotel into land, but you will not get depreciation on the land. This can be useful if you plan to develop the land (e.g., build a resort) or eventually build a primary residence on it after holding it as an investment property.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 4035.0,
      "endSec": 4082.7,
      "at": "1:07:15",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=4035",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-4035-rvzd6bgWVf731gDkNxHj4mtPXhuRp8.mp4",
       "dur": 150,
       "bytes": 9684598
      }
     },
     "alsoIn": []
    },
    {
     "title": "Lazy 1031: Same Calendar Year, No 45-Day Rule",
     "teaches": "The timing rules for a lazy 1031 versus a formal 1031 exchange.",
     "rule": "For a lazy 1031, you must buy the replacement property and put it in service between January 1 and December 31 of the same calendar year as the sale. There is no 45-day identification period or 180-day closing deadline like in a formal 1031 exchange.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3583.3,
      "endSec": 3629.5,
      "at": "0:59:43",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3583",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3583-5DJ1O5mOVMELfIAoMzMrgiNu3orEMU.mp4",
       "dur": 150,
       "bytes": 11785055
      }
     },
     "alsoIn": []
    },
    {
     "title": "Lazy 1031: Buy Enough Property to Offset All Income",
     "teaches": "How to size the replacement property in a lazy 1031 to fully offset depreciation recapture and other income.",
     "rule": "Add up all your income including depreciation recapture, then buy enough property (or properties) to offset that total. The replacement property may need to be twice as expensive or have enough depreciation to cover the recapture and other income. You can buy multiple properties in a lazy 1031.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3867.1,
      "endSec": 3917.4,
      "at": "1:04:27",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3867",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3867-jqcna5oA6gzCKqYFp1weKnOCG9m9uu.mp4",
       "dur": 150,
       "bytes": 10491268
      }
     },
     "alsoIn": []
    },
    {
     "title": "1031 Exchange: Real Estate to Real Estate Only",
     "teaches": "The types of properties that can be exchanged in a 1031 and the requirement for a real estate component.",
     "rule": "A 1031 exchange must be real estate to real estate. It can be any type of investment property (long-term rental, short-term rental, storage unit, land) as long as it has a real estate component. You cannot exchange real estate for a non-real-estate business like a car wash.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 3920.1,
      "endSec": 3967.0,
      "at": "1:05:20",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=3920",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-3920-ohLEqsu4dTHALa88KKYJxDS0LSVeCa.mp4",
       "dur": 150,
       "bytes": 9655510
      }
     },
     "alsoIn": []
    },
    {
     "title": "1031 exchange into a dream home",
     "teaches": "How to use a 1031 exchange to move equity from investment properties into a future primary residence without paying capital gains tax.",
     "rule": "Buy a property via 1031 exchange, rent it out for at least 2 years, then move in. The 2-year rental period is a good rule of thumb; longer is better. You must operate it as a genuine investment property (advertise, rent, make money) to show original intent.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": 4072.0,
      "endSec": 4119.7,
      "at": "1:07:52",
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view?t=4072",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-22-feb-11-2026-irr-and-roe-guest-brian-pate-4072-tJSUmPYfyzcedatUoEuHOHQwf20LRD.mp4",
       "dur": 150,
       "bytes": 9762705
      }
     },
     "alsoIn": []
    },
    {
     "title": "Airbnb tax benefits beat cash flow for W-2 earners",
     "teaches": "Members learn why STRs are prioritized for people with W-2 jobs: the tax benefit is worth more than the cash flow right now.",
     "rule": "For W-2 earners, the tax benefits of an Airbnb are worth more than the cash flow right now — but the cash flow compounds.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": 1156.1,
      "endSec": 1201.6,
      "at": "0:19:16",
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view?t=1156",
      "clip": {
       "url": "https://sgja14fsapeo12cq.public.blob.vercel-storage.com/clips/02-ev-call-24-feb-24-2026-four-ways-real-estate-pays-you-1156-muEgLt73LfmDBvT44M1MAkQREGDgxW.mp4",
       "dur": 150,
       "bytes": 14839387
      }
     },
     "alsoIn": []
    }
   ]
  }
 ]
};

export default airbnb;
