// AUTO-GENERATED by scripts/build_course_data.py — do not edit by hand.
// Member-only course data: bundled into the serverless function, never in public/.
const airbnb = {
 "id": "airbnb",
 "title": "The Airbnb Playbook",
 "subtitle": "Buy, launch and run short-term rentals — in lifecycle order",
 "blurb": "Buy, launch and run short-term rentals, in lifecycle order. Built from the Escape Velocity call archive — every lesson links to the recording it came from.",
 "moduleCount": 8,
 "lessonCount": 96,
 "sourceCalls": 20,
 "modules": [
  {
   "n": "0",
   "title": "Thesis — why Airbnb, and the velocity of money",
   "count": 12,
   "lessons": [
    {
     "title": "Refinance early to double your money every 2–3 years",
     "teaches": "Members learn the velocity strategy: pull equity out early via refinance, keep the property, and redeploy the capital into the next deal.",
     "rule": "If you can refinance in year 1, 2, or 3, you likely double your money or more. You still own the property, so you can repeat the process every 2–3 years instead of waiting 10 years.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Tax benefits can beat cash flow for W2 earners",
     "teaches": "Why one Airbnb a year can return more than the cash flow it produces when you still have a W2 job.",
     "rule": "If your tax bill is $100,000, buying one Airbnb a year can save and return roughly $100,000 — often double the ~$25,000/year of cash flow on a $2,000/month property. The tax benefit is worth more than the cash flow while you still have a W2, and the cash flow compounds.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Airbnb is the fastest path to financial freedom for W2 earners",
     "teaches": "Why Kassidy steers high-earning W2 members toward short-term rentals rather than small business acquisitions.",
     "rule": "For most people starting out, creating financial freedom through Airbnbs is the fastest way — small business buyers often take a year and 15 LOIs to close one deal, and many end up buying themselves another job.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 33 - Apr 14 2026 - Infinite Return BRRRR (guest Raj Chida)",
      "guest": "Raj Chida",
      "driveId": "16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB/view"
     },
     "alsoIn": []
    },
    {
     "title": "Equity is worth more than cash flow",
     "teaches": "Prioritize equity build-up over short-term cash flow when evaluating deals.",
     "rule": "The equity is like 10 times more valuable than the cash flow.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 965.5,
      "at": "0:16:05",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=965"
     },
     "alsoIn": []
    },
    {
     "title": "Airbnb is not dead — buy the right type",
     "teaches": "Ignore hype about Airbnb being dead; focus on unique stays or family compounds that still thrive.",
     "rule": "The two Airbnbs that will live on are unique stays (potato, tree houses) and family compound style (15-20+ people with amenities like putt putt, outdoor movie theater).",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 1262.4,
      "at": "0:21:02",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=1262"
     },
     "alsoIn": []
    },
    {
     "title": "The core STR model: short stays, high occupancy, above-market ADR",
     "teaches": "The baseline operating model for a short-term rental: target short stays, strong occupancy and above-average daily rates for the market.",
     "rule": "Target 2-3 night stays, ~70% occupancy, and above-average ADR for the market.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 2 - Sep 17 2025 - Velocity of Money and Trading Up",
      "guest": null,
      "driveId": "1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb",
      "startSec": 5953.0,
      "at": "1:39:13",
      "watch": "https://drive.google.com/file/d/1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb/view?t=5953"
     },
     "alsoIn": []
    },
    {
     "title": "Leverage plus forced appreciation is how you create wealth",
     "teaches": "The math behind why real estate builds wealth faster than stocks: you control a large asset with little cash, and any value you add goes straight to your equity.",
     "rule": "If you put 10% down on a $100,000 property ($10,000) and then spend $10,000 on renovations to increase value to $160,000, the $60,000 equity growth goes straight into your pocket.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Prioritize tax and lifestyle before equity",
     "teaches": "How to rank the four ways real estate pays you based on your personal situation so you pick the right deals.",
     "rule": "If you are a high-income W-2 earner with kids who wants to quit your job, tax benefits should be your biggest priority because your biggest lever is the tax benefit, not time. If you are broke, cash flow is your number one priority. Prioritizing lifestyle may mean sacrificing some equity (e.g. buying turnkey instead of a 7-month renovation).",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 940.9,
      "at": "0:15:40",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=940"
     },
     "alsoIn": []
    },
    {
     "title": "IRR measures the speed of your money, not just the size",
     "teaches": "The core distinction between ROI and IRR, and why velocity of money is the real metric.",
     "rule": "IRR (internal rate of return) is the compound rate of growth of your money over time. A 1000% ROI over 100 years is worse than a 50% return over 5 years. The standard benchmark for a deal is 15% IRR.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Cash on cash is the simple annual metric",
     "teaches": "How to quickly translate a cash-on-cash return into a payback period.",
     "rule": "Cash on cash is an annual metric: a 10% cash on cash means it takes 10 years to get your initial investment back. IRR, by contrast, accounts for the time your money is invested.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Hold period changes your IRR",
     "teaches": "Why the same return over different hold periods produces a different IRR.",
     "rule": "The same total return produces a different IRR depending on the hold period. Tripling your money over 10 years is a much lower IRR than tripling it over 5 years.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "IRR measures the speed of your money, not just the total return",
     "teaches": "Members learn that IRR is a velocity metric: the faster you get your capital back, the higher the IRR, even if the total multiple is the same.",
     "rule": "Tripling your money in 10 years is roughly a 10% IRR; tripling it in 5 years is roughly a 20% IRR. Cutting the hold period in half doubles the IRR if the multiple stays the same.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "1",
   "title": "Pick your market and your wedge",
   "count": 12,
   "lessons": [
    {
     "title": "Set a 30-day contract goal",
     "teaches": "The community's target for getting members under contract quickly.",
     "rule": "The goal for everyone in the community is to get under contracts within 30 days.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 2 - Sep 17 2025 - Velocity of Money and Trading Up",
      "guest": null,
      "driveId": "1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb",
      "startSec": 706.0,
      "at": "0:11:46",
      "watch": "https://drive.google.com/file/d/1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb/view?t=706"
     },
     "alsoIn": []
    },
    {
     "title": "Look at 20-40 properties before you buy one",
     "teaches": "The volume of on-the-ground property tours it takes to find a deal that actually meets your criteria.",
     "rule": "In Cleveland, Aaron looked at at least 20-25 properties and only one met the criteria. In Tucson, they looked at roughly 40 properties over three days before finding the right one. Block out a whole day (or multiple days) with your realtor and go see everything.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "The 20% rule for revenue to price",
     "teaches": "A quick screen to check whether a market and price point can support your revenue target.",
     "rule": "20% of the purchase price needs to be gross revenue. A $750,000 house needs to gross $150,000. Look for properties in that market already making $150,000 or more and study what they are doing so you can apply it.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 1750.8,
      "at": "0:29:10",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=1750"
     },
     "alsoIn": []
    },
    {
     "title": "Use the 20% rule to screen a deal fast",
     "teaches": "A quick screen to check whether a property's revenue can support its price before you go deeper.",
     "rule": "The 20% rule: the property must generate 20% of the purchase price in annual revenue. A $300,000 property needs $60,000/year in revenue to pass.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 20% rule sets your revenue target from list price",
     "teaches": "How to quickly screen whether a listing price can support a short-term rental before you dig into the P&L.",
     "rule": "Gross revenue must be roughly 20% of the purchase price — a $629K listing needs about $120K in gross revenue to work.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "RV parks require living on site under 20 acres",
     "teaches": "Why small RV parks and campgrounds often force you to live on site, making them a poor fit for many investors.",
     "rule": "If a campground is less than 20 acres, you likely cannot afford to outsource management at the beginning and will have to manage it yourself, often living on site. Anything above 20 acres gets scooped up by bigger players.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    },
    {
     "title": "Avoid hood Section 8 and focus on nicer neighborhoods",
     "teaches": "Members learn that the money in most markets is in nicer neighborhoods and to avoid hood Section 8 deals.",
     "rule": "The money is in the nicer neighborhoods. Don't touch hood Section 8 — you don't know the business plan or how to make money there.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 33 - Apr 14 2026 - Infinite Return BRRRR (guest Raj Chida)",
      "guest": "Raj Chida",
      "driveId": "16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB/view"
     },
     "alsoIn": []
    },
    {
     "title": "Target 25–30 unit management companies where the owner is still the operator",
     "teaches": "The sweet spot for acquiring a management business: big enough to have contracts, small enough that the owner is burnt out.",
     "rule": "Look for management companies around 25–30 units — that's where the seller is still the operator doing the servicing, isn't investing in growth, and is getting burnt out, which is the best opportunity.",
     "speaker": "Patryk Swietek",
     "source": {
      "label": "06 EV Call 39 - Jun 10 2026 - The First 10 Minutes (guest Patryk Swietek)",
      "guest": "Patryk Swietek",
      "driveId": "1Teqbc-6H9Slc26Nd9363b7m2r65rNR07",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Teqbc-6H9Slc26Nd9363b7m2r65rNR07/view"
     },
     "alsoIn": []
    },
    {
     "title": "Two homes on one property can hit $250–300K a year",
     "teaches": "How a main house plus ADU guest house can be run as one or two STR listings.",
     "rule": "A main house (3 bed/2 bath, ~1,600 sq ft) plus an ADU guest house (~1,000 sq ft) on one property can rent as one listing or two, producing $250–300K a year on a ~$1M all-in investment.",
     "speaker": "Zoey Berghoff",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Target the 2-bed 2-bath that nobody else offers",
     "teaches": "A specific wedge: the 2/2 is under-served because the market is either hotels or big luxury homes.",
     "rule": "Buy 2-bed 2-bath properties designed for couples, honeymoons and getaways — in her market the only alternatives are a hotel or a basement ADU, so a luxury 2/2 commands high rates with far less wear and tear than a 6-7 person home.",
     "speaker": "Zoey Berghoff",
     "source": {
      "label": "07 EV Call 20 - Jan 28 2026 - Land Hacking (guest Zoey Berghoff)",
      "guest": "Zoey Berghoff",
      "driveId": "1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1fZzyuBAF3fHfQqF4PS13KWj8ttMWnBeH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Don't rely on AirDNA averages—analyze top comps",
     "teaches": "How to use AirDNA data correctly to avoid underestimating revenue.",
     "rule": "AirDNA averages bundle the whole market and can be misleading. Look at the top-performing comps directly and pick the ones you believe you can match. Kassidy's properties are 5xing the AirDNA average.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 2 - Sep 17 2025 - Velocity of Money and Trading Up",
      "guest": null,
      "driveId": "1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb",
      "startSec": 5451.6,
      "at": "1:30:51",
      "watch": "https://drive.google.com/file/d/1oIMpiHYjdyfBwF8r1phUen5pjbpz8kSb/view?t=5451"
     },
     "alsoIn": []
    },
    {
     "title": "Use permits and supply constraints to pick a strong market",
     "teaches": "A market with capped permits and high demand creates high margins and strong revenue for short-term rentals.",
     "rule": "Look for markets with permit caps and high visitor demand. On Orcas Island, there are only 230 permits and they are not issuing more, yet way more than 230 people visit every day, making it a high-dollar, high-value, high-margin market.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "2",
   "title": "Underwrite before you tour",
   "count": 12,
   "lessons": [
    {
     "title": "Get under contract within 30 days",
     "teaches": "Set a hard deadline to get a property under contract to force action.",
     "rule": "In the next 30 days, you're going to be under contract on something.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 1997.7,
      "at": "0:33:17",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=1997"
     },
     "alsoIn": []
    },
    {
     "title": "Underwrite with the 2.5x equity multiple",
     "teaches": "What the 2.5x equity multiple means and how to calculate it for a short-term rental.",
     "rule": "Equity multiple is total return (forced appreciation + cash flow over 5 years, excluding tax benefits) divided by total cash in (down payment + furnishing + renovations). Target 2.5x or more. Example: if you put in $100k, you want $250k back.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Minimum 15% cash on cash return",
     "teaches": "How to use cash on cash to measure annual cash flow return and set a minimum threshold.",
     "rule": "Cash on cash = annual cash flow divided by total cash in. Minimum 15% unless equity growth is massive. Example: $33,000 annual cash flow on $100,000 invested is 33% cash on cash, paying back your investment in 3 years.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Target 20% IRR for speed of capital",
     "teaches": "What IRR measures and the target for short-term rental underwriting.",
     "rule": "IRR (internal rate of return) measures how quickly you get your return. Target 20% IRR, which means your 2.5x equity multiple happens in about 5 years.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "The OG 20% rule: revenue must be 20% of purchase price",
     "teaches": "The quick napkin-math screen to run before you buy any Airbnb: annual revenue should be at least 20% of the purchase price.",
     "rule": "Annual revenue must be at least 20% of the purchase price. A $500,000 property needs to bring in at least $100,000 in revenue. As purchase price goes higher, fixed costs don't rise as much, so you can flex down to about 15% at the most — but stick to 20% as your quick math.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 20% cash on cash rule",
     "teaches": "How to set a floor for the cash-flow return on your all-in initial investment.",
     "rule": "Cash flow divided by your all-in initial investment (down payment, furnishings, renovations, setup, and any hard money loan costs or fees) must be at least 20%. On a $150,000 all-in investment you need at least $30,000 a year in cash flow — meaning five years to get your money back on cash flow alone, not counting appreciation, debt paydown or a refinance.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 20% IRR rule and why you assume a five-year hold",
     "teaches": "How to measure the speed of your return, not just the size of it, using IRR.",
     "rule": "Add up all your cash flow, appreciation, debt paydown and tax benefits, assume a five-year hold, and the IRR needs to be 20%. Five years is the assumption because that's usually when your tax benefits run out and around when you might refinance. Stretch the hold to 10 years and the IRR will drop even though you're still earning a return.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "The bonus rule: 2.5x equity multiple",
     "teaches": "The single number that tells you whether you more than doubled your money over the hold.",
     "rule": "Your equity multiple needs to be 2.5x. Take everything you got over five years — cash flow, appreciation, a cash-out refi, debt paydown, tax savings — and it must be 2.5 times your initial investment. Put in $150,000 and you need $375,000 back. You want to more than double your money in five years.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "A real example of ignoring the 20% rule",
     "teaches": "A cautionary case study of buying on your own skills instead of the data.",
     "rule": "The Atlas (would-be island property) was bought for $835,000 — exactly what it was worth — and the data said $100,000 in revenue. They banked on their own skills instead of the 20% rule, hit just under $100,000 every year, and the market was oversaturated and reliant on waterfront to drive revenue. It never cash flowed, so they're selling it to take the equity elsewhere.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 20% rule is flexible at higher price points",
     "teaches": "How to adjust the revenue screen for more expensive properties.",
     "rule": "As purchase price goes up, the revenue percentage can flex down because fixed costs don't rise as much with a higher-priced property. Their Orcas Island property was bought for $880,000 and does $150,000 — just under 20% — and they also use it personally for a month a year. Fifteen percent is the floor at the most.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "The OG 20% rule: 20% cash on cash, 20% IRR, 2.5x equity multiple",
     "teaches": "The three-number screen Kassidy uses to judge whether a deal is worth doing.",
     "rule": "OG 20% rule: 20% cash on cash, 20% IRR, and 2.5x equity multiple.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 20% rule is about cash flow and flexes with purchase price",
     "teaches": "Members learn how the 20% rule works and why it can drop to 17-18% on higher-priced properties.",
     "rule": "The 20% rule is really about cash flow. As purchase prices get higher, the percentage can be less (18%, 17%) because fixed costs like utilities don't scale exponentially.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 33 - Apr 14 2026 - Infinite Return BRRRR (guest Raj Chida)",
      "guest": "Raj Chida",
      "driveId": "16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/16ILFYih2Br8ElvqXRa7_dApnDk3_tnpB/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "3",
   "title": "Structure and finance the purchase",
   "count": 12,
   "lessons": [
    {
     "title": "Use 401k cash for down payment proof of funds",
     "teaches": "A practical funding tactic when you don't have cash in your bank account but have funds in a 401k.",
     "rule": "If you need proof of funds for a down payment, you can show your 401k account balance if it has enough to cover more than the down payment.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Use vacation rental loan for 10% down",
     "teaches": "How to structure financing with a vacation rental loan to keep more cash and maximize leverage.",
     "rule": "If the property is 50+ miles from your home, you can use a vacation rental loan with 10% down instead of 20%, keeping more cash for reserves and emergencies.",
     "speaker": "Bobby",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Avoid PMI by putting 20% down",
     "teaches": "The tradeoff between putting less down and paying PMI, and when it makes sense to put more down.",
     "rule": "If you put under 20% down on a vacation/second home loan, you must pay PMI, which can be quoted very high; sometimes putting an extra 10% down to avoid PMI is the better tradeoff.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "A 10-year loan kills cash flow and tax benefits",
     "teaches": "Why a short amortization changes the deal profile and may not fit your buy box.",
     "rule": "A 10-year term at 5.75% means a substantially higher mortgage, lower cash flow, and no tax benefits — you own it sooner but it doesn't fit a cash-flow box.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 4455.7,
      "at": "1:14:15",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=4455"
     },
     "alsoIn": []
    },
    {
     "title": "Choose between Reg D 506 B and 506 C exemptions",
     "teaches": "Members learn the two primary SEC exemptions used by real estate investors and how to decide which one applies.",
     "rule": "99.9% of real estate deals use Reg D 506 B or 506 C. The choice depends on who your investors are and how you will reach them.",
     "speaker": "Bethany",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Limit non-accredited investors to 35 in a 506 B offering",
     "teaches": "Members learn the cap on non-accredited investors and how LLCs count toward that limit.",
     "rule": "In a 506 B offering, you can take up to 35 non-accredited investors. If an LLC invests, each member is counted separately unless all members are accredited.",
     "speaker": "Bethany",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Avoid general solicitation in a 506 B offering",
     "teaches": "Members learn what constitutes general solicitation and how it disqualifies a 506 B offering.",
     "rule": "In a 506 B offering, you cannot generally solicit or advertise, including mass emails, social media posts, or networking events, unless you have a substantial pre-existing relationship with every investor.",
     "speaker": "Bethany",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": [
      {
       "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
       "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view",
       "at": null
      }
     ]
    },
    {
     "title": "Verify accredited status reasonably in 506 B",
     "teaches": "Members learn that in a 506 B offering, they can rely on an investor's self-certification of accredited status unless they have reason to doubt it.",
     "rule": "In a 506 B offering, you do not need to verify accredited status; you can rely on the investor checking the box, unless you have reason to believe otherwise.",
     "speaker": "Bethany",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use 506(c) to advertise but only with accredited investors",
     "teaches": "The trade-off of using 506(c): you can generally solicit but must verify all investors are accredited.",
     "rule": "Under 506(c), you can advertise and generally solicit, but every investor must be accredited (income >$200k or net worth >$1M excluding primary residence).",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use 506(c) with a subscription agreement for small raises",
     "teaches": "Gives a cheaper compliance path for a small raise instead of paying for a full PPM.",
     "rule": "If a full PPM at $15,000 doesn't make sense for a $250,000 raise, either make the investors active or make sure they're accredited, verify them as accredited, and treat it as a 506(c). Put high-level risk disclosures in the subscription agreement — the document where they agree to give you the money — instead of doing a whole PPM. Don't make a bunch of statements before they come in that you have ",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Set a $50k minimum raise floor",
     "teaches": "What minimum investment to advertise when raising money for a deal.",
     "rule": "Advertise a minimum of $50k. You can take lower from friends and family if needed, but if people are testing you as a first-time operator, your advertised minimum sets the tone.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "How to structure investor equity splits for a 2.5x return",
     "teaches": "Members learn how to determine the equity split with investors by targeting a 2.5x equity multiple over five years, and how to calculate the split based on cash flow and appreciation.",
     "rule": "Aim for a 2.5x equity multiple for investors over five years. Typically, investors get 50-80% of equity, and you keep 20-50%, depending on how much they invest. Split cash flow based on equity percentage (e.g., 50/50 split means $500 each from $1000 leftover).",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "4",
   "title": "Design and furnish for revenue",
   "count": 12,
   "lessons": [
    {
     "title": "Budget $35–$50 per square foot for STR design",
     "teaches": "Members learn the minimum design budget per square foot that justifies a full design and furnishing production, so they don't underfund a project and end up disappointed.",
     "rule": "If a client isn't spending $35–$50 per square foot on designing their property, it's a no from the get-go — the budget won't justify the production and the end result will disappoint.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use 3D renders to manage guests during a renovation",
     "teaches": "Members learn how to keep existing bookings calm when buying an underperforming Airbnb and renovating it, by sharing realistic renders with guests ahead of arrival.",
     "rule": "When you buy an existing Airbnb with reservations already on the books and renovate it, send guests realistic 3D renderings of the finished property and tell them what to expect, rather than waiting until days before arrival to explain the change.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use 5.25 inch baseboards for a finished look",
     "teaches": "Baseboard sizing for a polished finish.",
     "rule": "Use 5.25 inch speed base if not doing square stock; 4 inch base is acceptable but 5.25 looks better.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view"
     },
     "alsoIn": []
    },
    {
     "title": "Add a jacuzzi for fast payback",
     "teaches": "A high-ROI amenity to add to a short-term rental.",
     "rule": "A new jacuzzi costs about $5K and pays for itself in under a year through higher revenue; add the jacuzzi first, then layer on a cold plunge and sauna.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Add a hot tub and sauna to boost revenue",
     "teaches": "How to use high-ROI amenities like a hot tub and sauna to increase bookings and revenue on a small STR.",
     "rule": "A $5,000 hot tub can pay for itself in under a year; budget about $20k for the hot tub, $15k for a sauna, and $10k for labor/setup, and add amenities like a jacuzzi first, then sauna.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Use a hero listing as your design and photo benchmark",
     "teaches": "How to identify a 'hero listing' and use it as the standard for your own design and photography.",
     "rule": "Find a hero listing with 90+ reviews, thoughtful non-cookie-cutter design, and photos with depth and low-angle wide shots; use it as your benchmark for your own listing.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Designers always come in over budget—negotiate to a hard cap",
     "teaches": "How to handle designer and GC budgets so you don't overpay for furnishing and renovation.",
     "rule": "Expect every designer to come in over budget. Take over the budget, combine all line items into a master budget, increase your initial budget by 70% if needed, then set a hard cap and require the designer to fit everything within it. Cut non-essential items like garage renovations or accent walls in every room; limit them to hero shots and main areas.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 18 - Jan 15 2026 - Fractional Funding (guest Stella Han)",
      "guest": "Stella Han",
      "driveId": "15jUOBQzPbrS5SuDqX8RxFTn3aKBu3Ahc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/15jUOBQzPbrS5SuDqX8RxFTn3aKBu3Ahc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Run natural gas to fire pits to avoid propane tank hassles",
     "teaches": "Why spending extra on a natural gas line for a fire pit improves guest experience and reduces maintenance.",
     "rule": "If you're installing a fire pit, pay the extra ~$2,000 to run natural gas instead of using propane. It eliminates swapping tanks, avoids running out mid-stay, and removes the eyesore of a propane tank. Small details like this matter at high nightly rates.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 18 - Jan 15 2026 - Fractional Funding (guest Stella Han)",
      "guest": "Stella Han",
      "driveId": "15jUOBQzPbrS5SuDqX8RxFTn3aKBu3Ahc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/15jUOBQzPbrS5SuDqX8RxFTn3aKBu3Ahc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Budget for wellness amenities: cheap vs. premium",
     "teaches": "Concrete cost ranges so members can decide how far to go on wellness amenities and what a premium build actually costs.",
     "rule": "You can check the wellness box for under $10k (sauna ~$3k, cold plunge ~$3k), but a premium wellness package runs $55–60k: sauna $25–30k, hot tub ~$10k, cold plunge $10–12k, plus stairs, lighting and the full experience build-out.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    },
    {
     "title": "Spend more than the next B&B over to win the market",
     "teaches": "The spend philosophy behind outperforming competing short-term rentals.",
     "rule": "If you can be profitable spending $30,000 on a property but have $100,000 available, put in the $100,000 — outspending the next B&B over is what produces the result and the proof.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    },
    {
     "title": "Wellness amenities are a spend that doesn't add equity but drives rate",
     "teaches": "Why investors who question amenity spend are the wrong investors, and how amenities pay back through rate and longevity.",
     "rule": "Expect to spend on wellness amenities (e.g. $65,000 in a backyard) that don't add to property equity — they buy nightly rate, guest quality and longevity, so only take capital that won't fight you on it.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    },
    {
     "title": "Say no to clients with insufficient design budget",
     "teaches": "Why you should turn down design clients whose budget won't cover the full production, to avoid disappointing results.",
     "rule": "If a client has a budget like $100,000 for a full design and outfit, it's not enough to justify the entire production and the end result will disappoint. Say no before they say no to you.",
     "speaker": "Sarah Glidewell",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "5",
   "title": "Launch and rank on Airbnb",
   "count": 12,
   "lessons": [
    {
     "title": "Write a listing that gets 10x the impressions and clicks",
     "teaches": "Why listing quality is both marketing and SEO, and what it earns you in Airbnb's algorithm.",
     "rule": "Set up your listing so people click and book and don't leave — that is marketing and search engine optimization at once. Kassidy's listings get 10x the impressions and clicks of anyone else in the market, which keeps Airbnb promoting them at the top of the list.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Check the 20% new listing discount to get promoted",
     "teaches": "How to use Airbnb's new listing promotion to boost visibility and get your first bookings.",
     "rule": "When launching, check the box for 20% off the first three bookings to get promoted to the top of search; block high-season or holiday dates or raise rates on those dates to avoid discounting them.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 20% first-bookings discount and five-star reviews",
     "teaches": "Your first three bookings determine your search ranking. Protect them.",
     "rule": "Check the box for the 20% discount on your first three bookings every time. Keep standard pricing and let the discount do the work. Getting five-star reviews on those first three bookings is the most important thing for your search ability.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 18 - Jan 15 2026 - Fractional Funding (guest Stella Han)",
      "guest": "Stella Han",
      "driveId": "15jUOBQzPbrS5SuDqX8RxFTn3aKBu3Ahc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/15jUOBQzPbrS5SuDqX8RxFTn3aKBu3Ahc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Check the 20% discount for first three bookings on launch",
     "teaches": "How to get initial bookings and reviews quickly by enabling Airbnb's new listing promotion.",
     "rule": "When launching, check the box to give a 20% discount to the first three people to book; this puts you at the top of search and guarantees three quick bookings.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view"
     },
     "alsoIn": []
    },
    {
     "title": "Get bookings and 5-star reviews as fast as possible",
     "teaches": "The importance of early bookings and reviews for Airbnb's algorithm and long-term success.",
     "rule": "The most important thing at launch is to get bookings and 5-star reviews as quickly as possible; don't worry about making all your money in month one.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view"
     },
     "alsoIn": []
    },
    {
     "title": "Get live by June 15 to capture July 4th",
     "teaches": "Members learn the deadline math for summer season: launch by mid-June to capture the July 4th booking window.",
     "rule": "Get the property live within 30 to 60 days, and by June 15 at the latest, so you can capture the July 4th booking.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view"
     },
     "alsoIn": []
    },
    {
     "title": "Airbnb direct booking links cut fees to 6%",
     "teaches": "Airbnb now gives each property a direct booking link with a 6% fee instead of the standard 15%, and you can still collect emails and retarget guests back to that link.",
     "rule": "Share your property's Airbnb direct booking link. Fees drop from 15% to 6% (you still pay 6% for background check and license upload via Hospitable). If you don't want true direct booking, collect emails and retarget them to the Airbnb link.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call - Sep 15 2026 - 30-Day Year-End Playbook",
      "guest": null,
      "driveId": "1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Check the 20% first-three-bookings discount at launch",
     "teaches": "The launch setting that pushes your listing up Airbnb's rankings.",
     "rule": "When you launch, check the box for the 20% discount to your first three bookings — it pushes you to the top of Airbnb rankings.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
      "guest": null,
      "driveId": "1IBSkQMG1pWkdqSBELz4drvHAOacHylmO",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view"
     },
     "alsoIn": []
    },
    {
     "title": "Be conservative when adding a resort fee",
     "teaches": "How to model ancillary revenue without overstating it.",
     "rule": "If you add a resort fee, model it very conservatively — e.g. $25/night times rooms times 30 nights at a 50% reduction.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 6861.6,
      "at": "1:54:21",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=6861"
     },
     "alsoIn": []
    },
    {
     "title": "Turn Instant Book on and build protections around it",
     "teaches": "How to get Airbnb promoting you while still screening risky guests.",
     "rule": "You absolutely have to have Instant Book on. Protect yourself with: automated follow-up messaging after booking that asks a question (cancel without penalty within 24 hours if they don't respond within ~12 hours and you feel uncomfortable), require ID/identity verification, set guest requirements, and a two-night minimum.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Set your baseline pricing from your target revenue",
     "teaches": "A simple math framework to set your initial nightly rate before using dynamic pricing tools.",
     "rule": "Decide how much money you want to make, then calculate the ADR needed to hit that number (e.g., $100k target) to establish your baseline min and max rates.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Hot tub is the number one filter — use filterable amenities",
     "teaches": "Guests filter by hot tub more than anything else. Filterable amenities push you to the top of search even with weak photos.",
     "rule": "Prioritise filterable amenities like hot tub because it's the number one filter guests use. In Ann Arbor, 785 homes dropped to 79 when filtering for hot tub — only 10% of listings have one, so adding one puts you in the top 10%.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 EV Call 9 - Nov 5 2025 - Listing Optimization",
      "guest": null,
      "driveId": "1xI3nQLC2thLMvWxRCpyKTSlwfe3Dov9E",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1xI3nQLC2thLMvWxRCpyKTSlwfe3Dov9E/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "6",
   "title": "Run it like a micro hotel",
   "count": 12,
   "lessons": [
    {
     "title": "Manage your first property yourself for 3-6 months",
     "teaches": "Why self-managing your first STR teaches you the operations, software, and seasonal issues that set you up to scale later.",
     "rule": "Manage your first property yourself for 3-6 months (or a full year to see all seasons) before outsourcing, unless you absolutely cannot.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use a VA instead of a 20% property manager",
     "teaches": "How to save on management fees by hiring a VA to run your tech stack and coordinate maintenance instead of paying a full-service manager.",
     "rule": "Hire a VA to manage your tech stack and call out maintenance people; this is more efficient than paying 20% of revenue to a property manager.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view"
     },
     "alsoIn": []
    },
    {
     "title": "Hire a revenue manager for 4% to boost revenue",
     "teaches": "Why a specialized revenue manager can pay for themselves by increasing your revenue through active demand-based pricing.",
     "rule": "Consider hiring a revenue manager who charges around 4% of revenue; if they increase your revenue by 10%, it pays for itself.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view"
     },
     "alsoIn": []
    },
    {
     "title": "Don't heat a freshly replastered pool for about 20 days",
     "teaches": "A pool replaster timeline rule that affects when you can actually rent the property.",
     "rule": "After a pool is replastered it must cure about four weeks, and you cannot heat the pool or an in-ground spa for about 20 days after plastering.",
     "speaker": "Chris",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view"
     },
     "alsoIn": []
    },
    {
     "title": "Hire an offshore VA for guest messaging instead of a 20% PM",
     "teaches": "The cost case for hiring an offshore virtual assistant to handle guest messaging and maintenance coordination versus a traditional property manager.",
     "rule": "An offshore VA runs about $1,500/month for ~40 hours/week, versus a property management company taking 20% off the top — a huge cost difference.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    },
    {
     "title": "Interview 20 VAs and use scenario questions",
     "teaches": "How to screen guest-messaging hires so you don't end up with someone who refunds guests indiscriminately.",
     "rule": "Interview roughly 20 candidates and ask scenario questions (e.g. 'the hot tub isn't working — walk me through your steps, what would you tell the guest, would you offer a refund?') to test problem-solving and objectivity.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use two VAs to cover 24/7 messaging",
     "teaches": "Why one person can't cover guest messaging around the clock and how to split it.",
     "rule": "Expecting 24-hour, 7-day coverage from one person is too much — use two people who swap shifts so coverage is always maintained.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    },
    {
     "title": "Offshore VA tiers start at 10 hours a week",
     "teaches": "You don't need to commit to full-time help to get messaging support.",
     "rule": "Offshore companies offer tiered support — many clients use them for just 10 hours a week for calendar, scheduling or extra support, so you don't have to jump straight to full-time.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    },
    {
     "title": "Budget roughly $1,500/month for a VA across a portfolio",
     "teaches": "A concrete cost benchmark for outsourcing guest messaging and maintenance coordination across multiple properties.",
     "rule": "Pay the VA around $1,500 per month for a bucket of hours across all properties, regardless of message volume. Fill extra hours with useful tasks like making Canva signs for sauna/hot tub instructions.",
     "speaker": "Erin",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    },
    {
     "title": "Collect W9s before any work starts",
     "teaches": "Members learn the sequencing rule for contractor paperwork so they can actually issue 1099s at year end.",
     "rule": "Get the W9 before the contractor does any work — once they're paid they often won't hand over their SSN or EIN, and without that info you can't file a 1099.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    },
    {
     "title": "Give guests 24 hours notice on late checkout requests",
     "teaches": "Members learn the cutoff for promising a late checkout without wrecking the cleaner's day.",
     "rule": "Tell guests you likely can't accommodate a late checkout with less than 24 hours notice; even inside 48-72 hours, check with cleaners before promising it.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    },
    {
     "title": "Win the first 10 minutes",
     "teaches": "How to intentionally design the guest arrival experience so the first 10 minutes create a positive confirmation bias for the rest of the stay.",
     "rule": "The first 10 minutes determine whether you get a good review; everything after is confirmation bias. Design the arrival so it is as close to perfect as possible.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 39 - Jun 10 2026 - The First 10 Minutes (guest Patryk Swietek)",
      "guest": "Patryk Swietek",
      "driveId": "1Teqbc-6H9Slc26Nd9363b7m2r65rNR07",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Teqbc-6H9Slc26Nd9363b7m2r65rNR07/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "7",
   "title": "Equity, ADUs and tax",
   "count": 12,
   "lessons": [
    {
     "title": "The lazy 1031: stay under the capital gains threshold",
     "teaches": "Members learn how to avoid federal capital gains tax by keeping reportable income below the threshold in a year they sell appreciated assets.",
     "rule": "If you get your reported AGI below roughly $92K (married), you pay no federal capital gains tax — so sell assets early in the year and buy STRs to push income down.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use the 7-day rule for STR tax treatment",
     "teaches": "To qualify as a short-term rental for tax purposes, the average guest stay must be 7 days or less.",
     "rule": "The average nightly stay must be 7 days or less to qualify as a short-term rental for tax purposes. This is easy to maintain as long as you're not using it as a midterm rental.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 3770.6,
      "at": "1:02:50",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=3770"
     },
     "alsoIn": []
    },
    {
     "title": "Estimate tax savings at 20-30% of purchase price",
     "teaches": "A quick conservative rule for projecting first-year tax write-offs.",
     "rule": "Tax savings from a short-term rental are roughly 20-30% of the purchase price, depending on your income. On a $1M property that's $200K-$300K of write-off against W2 income.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "1031 exchange to avoid depreciation recapture tax",
     "teaches": "Members learn that selling without a 1031 exchange triggers depreciation recapture taxed as ordinary income, which can exceed the cash received from the sale.",
     "rule": "If you sell a short-term rental without a 1031 exchange, all depreciation taken is recaptured and taxed at your ordinary income rate. Example: $400,000 depreciation at 32% = $120,000 tax, which can be more than the $100,000 cash you receive from the sale.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "1031 from residential to commercial is cleaner",
     "teaches": "Members learn why 1031 exchanging into a commercial property like a hotel is easier than residential-to-residential because you control the closing timeline.",
     "rule": "With commercial property, you have a PSA and a known closing date (often 90 days), so you can list and sell your property within the 45-day identification window. Residential-to-residential 1031s are harder because buyers won't wait for your sale.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use a 1031 to trade up and build equity",
     "teaches": "Members learn how repeated 1031 exchanges can turn small equity into large equity over time.",
     "rule": "Trade up from residential to commercial properties using 1031 exchanges to defer taxes and boost value. Example: a $65,000 HELOC on a primary residence was used to buy land, which was sold and 1031 exchanged into a property now worth $800,000 in equity.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use the lazy 1031 to wipe out depreciation recapture",
     "teaches": "If you sell a property and fail or skip a formal 1031, you can still offset the depreciation recapture by buying another property in the same calendar year.",
     "rule": "The lazy 1031: sell a property, then buy enough property to offset all your income including the depreciation recapture, all within the same calendar year (Jan 1 to Dec 31). No 45-day identification window applies.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "A 1031 is more efficient than the lazy 1031",
     "teaches": "Why the formal 1031 beats the lazy 1031 even though the lazy 1031 is easier.",
     "rule": "With a 1031 the recapture just disappears and you get a whole new set of depreciation and cost segregation on the new property. With the lazy 1031 you must spend some of the new property's depreciation just to cover the recapture from the property you sold, so it is less efficient.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "1031 into your future dream home",
     "teaches": "A strategy to move investment property equity into a personal residence tax-deferred.",
     "rule": "1031 investment property into a home you want to live in, rent it out for at least two years operating it as a real investment (advertise it, make money on it), then move in. Longer than two years is better.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Cost segregation can wipe out W-2 taxes",
     "teaches": "How a cost segregation study on an STR offsets active income.",
     "rule": "On a $1.5M property, a cost segregation study can generate over $500k of first-year depreciation deduction — enough to pay $0 in taxes for about five years on a $200k salary.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use cost segregation to wipe out W2 taxes on an Airbnb",
     "teaches": "How a cost segregation study on a short-term rental lets a W2 earner offset active income, and roughly how much you can write off.",
     "rule": "A cost segregation study breaks the building value into components (windows, doors, roof, landscaping, pool) on 5- or 7-year schedules that you can accelerate. Estimate you can write off 20-40% of the purchase price in year one. Example: a $1M property with 20% land value gives $800K of building value to depreciate.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 100-hour material participation rule for short-term rentals",
     "teaches": "The time-tracking requirement that lets a W2 earner take Airbnb depreciation losses against active income without being a real estate professional.",
     "rule": "You must put in at least 100 hours in the first year and more hours than any single other individual (including a property manager). Track your hours and mileage in a spreadsheet — QuickBooks and mileage apps work. Documentation matters if the IRS audits.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    }
   ]
  }
 ]
};

export default airbnb;
