// AUTO-GENERATED by scripts/build_course_data.py
import airbnb from './airbnb.js';
import tax from './tax.js';

const courses = { airbnb, tax };

export function catalogue() {
  return Object.values(courses).map((c) => ({
    id: c.id, title: c.title, subtitle: c.subtitle, blurb: c.blurb,
    moduleCount: c.moduleCount, lessonCount: c.lessonCount, sourceCalls: c.sourceCalls,
    modules: c.modules.map((m) => ({ n: m.n, title: m.title, count: m.count })),
  }));
}

export default courses;
