// AUTO-GENERATED by scripts/build_course_data.py — do not edit by hand.
// Member-only course data: bundled into the serverless function, never in public/.
const tax = {
 "id": "tax",
 "title": "The Tax Playbook",
 "subtitle": "Depreciation, cost segregation, REP, entities and the year-end deadline",
 "blurb": "The tax side of the portfolio: depreciation, cost segregation, the real estate professional, entities and the year-end deadline — taught on Kassidy's own calls.",
 "moduleCount": 8,
 "lessonCount": 88,
 "sourceCalls": 21,
 "modules": [
  {
   "n": "0",
   "title": "Tax is the fourth lever — why real estate refunds your tax bill",
   "count": 12,
   "lessons": [
    {
     "title": "Under $150,000 combined income can use bonus depreciation",
     "teaches": "If combined income as a couple is under $150,000, you can use bonus depreciation without the STR loophole.",
     "rule": "If you make less than $150,000 combined as a couple, you can use bonus depreciation.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV Call - Sep 04 2026 - Friday Call (moved)",
      "guest": null,
      "driveId": "1EmH6XLFrnplinXKpEd1lckR58hWHH_TM",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1EmH6XLFrnplinXKpEd1lckR58hWHH_TM/view"
     },
     "alsoIn": []
    },
    {
     "title": "Depreciation as a paper loss for W-2 employees",
     "teaches": "How depreciation on a short-term rental can refund taxes for W-2 employees, 1099 contractors, or small business owners.",
     "rule": "If you make $300,000 a year and pay $75,000 in taxes, a $100,000 house can get your $75K back in year one; a $400,000 house can get about half that or more in the following year; a $1,000,000 house can get that $75K back over three to four years.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Quick tax savings estimate: 20 to 30% of purchase price",
     "teaches": "A conservative shortcut for estimating the tax write-off a property will generate against active income.",
     "rule": "Tax savings is 20 to 30% of the purchase price — a $1,000,000 property gives a $200,000 to $300,000 write-off, conservatively.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Sacramento's 180-day rental cap limits short-term rental income",
     "teaches": "Some markets cap short-term rentals at 180 days per year unless owner-occupied, which can severely limit revenue and tax benefits.",
     "rule": "In Sacramento you can only rent it out for 180 days of the year unless it's owner-occupied.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "One Airbnb a year can refund a $100,000 tax bill",
     "teaches": "Members see the scale of the tax refund relative to cash flow, and why the tax benefit is worth more than cash flow right now for W2 earners.",
     "rule": "If your tax bill is $100,000, you can save and get back $100,000 every year with buying one Airbnb a year. Even $60,000 or $50,000 back in taxes every single year is double a $2,000/month ($25,000/year) cash flow example.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Tax benefits can beat cash flow for W2 earners",
     "teaches": "Why one Airbnb a year can return more than the cash flow it produces when you still have a W2 job.",
     "rule": "If your tax bill is $100,000, buying one Airbnb a year can save and return roughly $100,000 — often double the ~$25,000/year of cash flow on a $2,000/month property. The tax benefit is worth more than the cash flow while you still have a W2, and the cash flow compounds.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Tax efficiency is scored against your active income",
     "teaches": "The tax-efficiency score in Kassidy's calculator is driven by your active income, not the property price, so you must know your active income to size the offset.",
     "rule": "Tax efficiency is based off of your W2 income; if you will have more income than that, include it so you know how much you need to offset.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Extra cash down can be evaluated as an ROI calculation",
     "teaches": "Putting more cash down to improve cash flow should be weighed as a return-on-investment calculation, especially for investors with W-2 income seeking tax benefits.",
     "rule": "An extra 5% down on a $500k purchase is $25k; if it creates an extra $5k of cash flow, it takes five years to get that money back.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Depreciation return equals your tax bracket, and brackets diminish",
     "teaches": "The value of a depreciation deduction is the tax bracket it offsets, so using it all at once can waste it in lower brackets.",
     "rule": "If you are in the 36% tax bracket, depreciation gives you a 36% return; as you use more, you drop into the 30%, 24%, and eventually 10%, 12%, 14% brackets, so taking all $400,000 at once creates diminishing returns and wastes depreciation on lower brackets when you could save more next year.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "Opportunity cost of a primary home vs. renting and buying a short-term rental",
     "teaches": "Members see the five-year math comparing buying a $1.5M primary residence against renting a similar house and putting the same capital into a $500K short-term rental.",
     "rule": "On a $1.5M primary with 10% down, you pay about $660,000 in mortgage, insurance, and taxes over 5 years, gain about $620,000 of equity, and after the $150,000 down payment you are down about $200,000 over five years. Renting the same house at $4,000/month and buying a $500,000 short-term rental with 20% down plus $50,000 in furnishings and renovations (also $150,000 total) at $100,000 gross revenu",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "One short-term rental buys back eight months with your kids",
     "teaches": "Members see the time value of a single short-term rental measured in family time rather than dollars.",
     "rule": "You get 144 months from a child's birth to when they leave the house. Working eight hours a day plus one hour of commute spends 40% of your time at work. One average $500,000 short-term rental doing $100,000 gross revenue and $45,000 net income — counting cash flow, equity growth, and tax benefits, and assuming you make $70 an hour — buys you an extra eight months with your kids and family.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": [
      {
       "label": "02 EV Call 27 - Mar 18 2026",
       "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view",
       "at": null
      }
     ]
    },
    {
     "title": "Self-employed pay both halves of self-employment tax",
     "teaches": "Understanding why 1099 self-employed individuals are taxed more than W-2 employees.",
     "rule": "As an employee, you pay 7.5% and the employer pays 7.5% of your taxes. As a self-employed 1099, you pay both halves, totaling 15%.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 16 - Dec 31 2025 - Year End and Listing Momentum",
      "guest": null,
      "driveId": "1in7aRZETqt36nXE2ciSUCnN9uU6aAuUH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1in7aRZETqt36nXE2ciSUCnN9uU6aAuUH/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "1",
   "title": "Depreciation and cost segregation — the first-year decision",
   "count": 12,
   "lessons": [
    {
     "title": "Cost seg on midterm/long-term can't offset W-2 income",
     "teaches": "Even with cost segregation, midterm and long-term rental losses cannot offset W-2 income.",
     "rule": "What you can't do, still, is offset the losses against your W-2 income.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV Call - Sep 04 2026 - Friday Call (moved)",
      "guest": null,
      "driveId": "1EmH6XLFrnplinXKpEd1lckR58hWHH_TM",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1EmH6XLFrnplinXKpEd1lckR58hWHH_TM/view"
     },
     "alsoIn": []
    },
    {
     "title": "W4 exemption to keep cash for cost segregation down payments",
     "teaches": "A strategy for W2 earners who are buying properties they will cost seg: adjust withholding to keep cash for down payments.",
     "rule": "If you know you are buying Airbnbs or hotels that you are going to cost seg, fill out the W4 and essentially be exempt so you are not paying any taxes throughout the year and get to keep all your cash. Then instead of paying your normal taxes, you keep that money and use it as a down payment on your next property. Check with your CPA.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "Cost segregation splits building value roughly 50/50",
     "teaches": "How a cost segregation study divides a property's depreciable basis between accelerated components and the building itself.",
     "rule": "On a $1,000,000 property with 20% land, the $800,000 building value is roughly 50/50: about $400,000 in cost-seg components (windows, doors, bathrooms, tile, landscaping) that can be accelerated, and about $400,000 in the building itself that is still depreciated over 27.5 years.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "The building basis still depreciates over 27.5 years",
     "teaches": "Even with 100% bonus depreciation on cost-seg assets, the building portion remains on a 27.5-year schedule.",
     "rule": "The building portion is not accelerated: $400,000 over 27.5 years works out to roughly $15,000 per year of depreciation.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "Depreciation is a paper loss that offsets W2 income",
     "teaches": "Depreciation is a paper loss that lets you subtract income from your W2, producing a big deduction and potentially a refund.",
     "rule": "Roughly 30% of the purchase price — closer to 40% depending on the market — can be subtracted from your income in the first year.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Rough math: 30-40% of purchase price in year one",
     "teaches": "The rough first-year write-off from a property purchase, using a million dollar property as the example.",
     "rule": "Rough math is about 30% of the purchase price, probably closer to 40% depending on where you're looking; 40% of the purchase price you get to subtract off of your income in the first year.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Worked example: $500K income, $1M Airbnb, $400K write-off",
     "teaches": "How the deduction flows through to a refund, using Kassidy's own numbers.",
     "rule": "If you make 500K and buy a million dollar Airbnb, 40% of that ($400K) is written off against the 500K, so 400K becomes $100,000, let's just say $92,000; tax bill at 92K is like 12 grand or less, so if you paid 100 grand in taxes all year you get an $80,000 check back.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Example: $250k salary, $550k Airbnb, $600k bonus depreciation write-off",
     "teaches": "How bonus depreciation on a short-term rental can offset W-2 income and generate a tax refund.",
     "rule": "With a $250,000 salary, buying a $550,000 Airbnb with $120,000 down (20%), $50,000 renovations and furnishings, and $50,000 land value yields a $600,000 write-off due to bonus depreciation. You only need $300,000 to offset income, resulting in $0 reported income and a $75,000 refund.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 16 - Dec 31 2025 - Year End and Listing Momentum",
      "guest": null,
      "driveId": "1in7aRZETqt36nXE2ciSUCnN9uU6aAuUH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1in7aRZETqt36nXE2ciSUCnN9uU6aAuUH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Cost segregation can accelerate more than the 25% rule of thumb",
     "teaches": "Members learn that the common 25% cost segregation assumption is conservative and that 100% bonus depreciation can potentially be applied to the full structure value.",
     "rule": "The rule of thumb is about 25% of the total purchase price of the home is bonus depreciated, but you can do more; with 100% bonus depreciation you could accelerate the full structure value in year one.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
      "guest": null,
      "driveId": "1IBSkQMG1pWkdqSBELz4drvHAOacHylmO",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view"
     },
     "alsoIn": []
    },
    {
     "title": "Only assets under 30-year depreciation can be accelerated",
     "teaches": "Members learn that cost segregation buckets assets into 3, 5, 10, and 15-year categories, and only those shorter-life assets can be fast-forwarded to year one.",
     "rule": "Only stuff that isn't considered depreciable over 30 years can be fast-forwarded 100% to year one; other parts go into 3, 5, 10, and 15-year buckets.",
     "speaker": "Member (call participant)",
     "source": {
      "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
      "guest": null,
      "driveId": "1IBSkQMG1pWkdqSBELz4drvHAOacHylmO",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view"
     },
     "alsoIn": [
      {
       "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
       "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view",
       "at": null
      }
     ]
    },
    {
     "title": "The 25% of purchase price rule of thumb is conservative",
     "teaches": "Members learn that the common 25%-of-purchase-price estimate for accelerated depreciation is on the low end and can be exceeded.",
     "rule": "The rule of thumb is about 25% of the total purchase price, but you can do more — 25% may even be conservative.",
     "speaker": "Member (call participant)",
     "source": {
      "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
      "guest": null,
      "driveId": "1IBSkQMG1pWkdqSBELz4drvHAOacHylmO",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view"
     },
     "alsoIn": []
    },
    {
     "title": "Match the deal to your goals, not the market",
     "teaches": "How to choose between cash flow and equity/tax plays based on your personal situation.",
     "rule": "If you don't need cash flow because you have high W-2 income, buy something you can flip into a lot of equity with tax benefits rather than chasing cash flow — and look at your own backyard before assuming a saturated market like the Caribbean won't work.",
     "speaker": "Kassidy",
     "source": {
      "label": "03 EV Call 19 - Jan 21 2026 - Raising Money for STRs (guest Sarah Glidewell)",
      "guest": "Sarah Glidewell",
      "driveId": "1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1sv9cPnv1dcNYiCLvBY1bAcH01WG3NkN8/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "2",
   "title": "Repairs, improvements and where renovation dollars really go",
   "count": 12,
   "lessons": [
    {
     "title": "The 30-day year-end playbook",
     "teaches": "Members get a step-by-step 30-day plan to get a property under contract, close 30 days later, and get it in service 30 days after that to reduce this year's tax bill.",
     "rule": "In 30 days: pick your market, visit it, get a realtor, get pre-approval, underwrite 20 properties a week, submit offers, and stay active in the chat. Then close 30 days later and get in service 30 days after that.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call - Sep 15 2026 - 30-Day Year-End Playbook",
      "guest": null,
      "driveId": "1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Improvements specifically for the rental unit add to cost basis",
     "teaches": "Renovation dollars spent specifically on the rented portion increase the depreciable cost basis.",
     "rule": "If you bought for $500,000 and later spent $100,000 specifically on the mother-in-law unit, you add that $100,000 to your cost basis and can depreciate it. But if you spend $100,000 on the garage and guests don't use the garage, you don't get to take that depreciation.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view"
     },
     "alsoIn": []
    },
    {
     "title": "Paying cash for improvements increases immediate depreciation",
     "teaches": "Members learn that coming out of pocket for an improvement like a pool means the full amount goes toward depreciation immediately rather than being financed.",
     "rule": "If you don't finance the pool, the full 100 goes towards the depreciation immediately.",
     "speaker": "Taylor (call participant)",
     "source": {
      "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
      "guest": null,
      "driveId": "1IBSkQMG1pWkdqSBELz4drvHAOacHylmO",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view"
     },
     "alsoIn": []
    },
    {
     "title": "Know what you're investing for before you judge a deal",
     "teaches": "Why a low cash-on-cash can still be a great deal if the equity or tax outcome is outsized.",
     "rule": "The rules flex depending on what you're investing for. If your projected cash on cash is lower but your equity is way outsized, it can still be a good deal. If you're going to save $200,000 on your tax bill this year — money you'd otherwise have to pay — factor that in. But on a straight return basis, it's 2.5x on your money.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "Don't spend more improving a property than the value it adds",
     "teaches": "The mistake that put many Airbnb owners underwater, and how to avoid it.",
     "rule": "If you pour $300,000 into a property but the value only goes up $150,000, you're underwater by $150,000. Even a 30% cash on cash means roughly three years just to break even, and by then your tax savings are running out. Create equity in the property — don't just rely on cash flow.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 49 - Aug 26 2026 - Three 20 Percent Rules",
      "guest": null,
      "driveId": "1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1KUpjAEvBJZxsYE2hKApv5xURjAPuphhY/view"
     },
     "alsoIn": []
    },
    {
     "title": "Don't include tax savings in your deal analysis",
     "teaches": "Why you should keep tax benefits out of your underwriting and treat them as a bonus, not a return driver.",
     "rule": "Never include tax savings in your return calculations. Tax savings are fun to look at but should not be part of the deal analysis because depreciation may be recaptured unless you 1031 exchange or hold long-term.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 8 - Oct 29 2025 - ADU Velocity",
      "guest": null,
      "driveId": "1IBSkQMG1pWkdqSBELz4drvHAOacHylmO",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1IBSkQMG1pWkdqSBELz4drvHAOacHylmO/view"
     },
     "alsoIn": []
    },
    {
     "title": "Verify the listed square footage",
     "teaches": "Listing square footage can be wrong, which throws off your revenue and depreciation math.",
     "rule": "Verify the actual square footage before underwriting — a 750 sq ft 2-bedroom may not realistically do $100k.",
     "speaker": "Kassidy",
     "source": {
      "label": "04 EV Call 30 - Apr 1 2026 - Design for Vibe and ROI (Erin)",
      "guest": null,
      "driveId": "17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/17j8TEagXtQeq8LHuY5qjthEEj0LQlVa5/view"
     },
     "alsoIn": []
    },
    {
     "title": "Construction expenses can be written off against active income",
     "teaches": "Construction expenses that are not put in a depreciation bucket can be treated as business expenses and written off against active income, but this can hurt your debt-to-income ratio.",
     "rule": "Construction expenses that are not put in a depreciation bucket can be written off against active income as a share of the loss. However, if you take all construction stuff as expenses in that year, the bank cannot back them out, making it harder to get approved for loans because your income looks lower.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view"
     },
     "alsoIn": []
    },
    {
     "title": "Put improvements into depreciation accounts to protect debt-to-income ratio",
     "teaches": "When doing improvements in the beginning, plug all of those into depreciation accounts so you can accelerate depreciation and the bank can back out depreciation when calculating your income for loans.",
     "rule": "When you're doing your improvements in the beginning, plug all of those into the depreciation accounts so that you can take it as depreciation and accelerate it just like you would the rest of the property. This does not affect your debt-to-income ratio because the bank can back out depreciation. If you take expenses, it shows as actual cost and the bank can't back those out.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view"
     },
     "alsoIn": []
    },
    {
     "title": "Renovations are less tax-efficient than buying a new asset",
     "teaches": "Money spent on renovations is not as tax-advantaged as buying a new property because renovations are not leveraged.",
     "rule": "Renovations are at best a one-to-one write-off, while buying a new asset with leverage can give a three-to-one tax benefit.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    },
    {
     "title": "Know your buy box: cash flow, equity, or tax benefits",
     "teaches": "The three reasons to buy a short-term rental and how to decide which you're optimizing for.",
     "rule": "When looking at deals, understand whether you're buying for cash flow, equity, or tax benefits, or a weighted version of all three.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "Verify title transfer and permits in a partnership",
     "teaches": "A partnership failure mode: managing partners responsible for title, permits and compliance may never actually do it, and you get shut down.",
     "rule": "In a partnership, assign and verify that title gets transferred into the entity's name and that permits are good. In this deal the managing partners never transferred title, and they were fine until they got shut down.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 43 - Jul 8 2026 - Positioning Workshop (guest Katie Cline)",
      "guest": "Katie Cline",
      "driveId": "1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI",
      "startSec": 6711.7,
      "at": "1:51:51",
      "watch": "https://drive.google.com/file/d/1S_jYIkDX0F2XAEVqcDTp0McJPms-06cI/view?t=6711"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "3",
   "title": "The real estate professional and the STR loophole",
   "count": 12,
   "lessons": [
    {
     "title": "Over $150,000 requires the STR loophole to offset active income",
     "teaches": "Above $150,000 combined income, the only way to take a loss against active income is short-term renting and bonus depreciating.",
     "rule": "If you make over $150,000, the only way to take a loss against your active income is by doing the short-term rental and bonus depreciating, and it has to be short-term rented, not midterm.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV Call - Sep 04 2026 - Friday Call (moved)",
      "guest": null,
      "driveId": "1EmH6XLFrnplinXKpEd1lckR58hWHH_TM",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1EmH6XLFrnplinXKpEd1lckR58hWHH_TM/view"
     },
     "alsoIn": []
    },
    {
     "title": "Passive losses cannot offset active income over $150,000",
     "teaches": "The passive activity rule that blocks long-term rental losses against W-2 income for higher earners.",
     "rule": "For anyone making over $150,000 combined, you cannot take passive losses against your active income; a long-term rental is passive, so its depreciation cannot offset active income.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "The STR loophole is the only way to take depreciation against active W-2 income",
     "teaches": "Why the short-term rental loophole is powerful for W-2 employees.",
     "rule": "The short-term rental loophole is the only thing that allows you to take depreciation off of your active income as a regular W-2 employee.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "$150,000 income threshold for depreciation against active income",
     "teaches": "The income limit that determines whether you can use depreciation from long-term rentals to offset active income.",
     "rule": "If you make less than $150,000 a year as a salary employee or 1099, you can take depreciation to offset your income; if you make over $150,000, you cannot.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "W2 income disqualifies you from real estate professional status",
     "teaches": "A W2 job will cause the IRS to automatically deny real estate professional status, so you need to structure your work accordingly.",
     "rule": "If you have a W2, the IRS will automatically say you are not a real estate professional.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Getting reported income below $92K with a short-term rental",
     "teaches": "Buying a short-term rental lets you cost-segregate and depreciate to push your reported income below the $92,000 threshold so you avoid capital gains.",
     "rule": "You need to get your reported income below about $92K; buying a short-term rental lets you cost-segregate and depreciate to get a big write-off.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Two W-2 partners cannot both use the STR loophole",
     "teaches": "If two partners both have W-2 jobs and neither is a real estate professional, only one can take active losses from a short-term rental against their income.",
     "rule": "Only one person can claim the STR loophole unless one partner is a real estate professional. If both have W-2 jobs, they cannot both take active losses.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view"
     },
     "alsoIn": []
    },
    {
     "title": "W-2 income can block real estate professional status",
     "teaches": "Having a W-2 job can prevent you from qualifying as a real estate professional, but a spouse may be able to qualify.",
     "rule": "If you have a W-2, you are locked in to not having REP status; a spouse with a flexible job can get REP status.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 16 - Dec 31 2025 - Year End and Listing Momentum",
      "guest": null,
      "driveId": "1in7aRZETqt36nXE2ciSUCnN9uU6aAuUH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1in7aRZETqt36nXE2ciSUCnN9uU6aAuUH/view"
     },
     "alsoIn": []
    },
    {
     "title": "A 10-year loan kills cash flow and tax benefits",
     "teaches": "Why a short amortization changes the deal profile and may not fit your buy box.",
     "rule": "A 10-year term at 5.75% means a substantially higher mortgage, lower cash flow, and no tax benefits — you own it sooner but it doesn't fit a cash-flow box.",
     "speaker": "Kassidy",
     "source": {
      "label": "01 EV Call 29 - Mar 25 2026 - Market Selection",
      "guest": null,
      "driveId": "1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3",
      "startSec": 4455.7,
      "at": "1:14:15",
      "watch": "https://drive.google.com/file/d/1Gb6E1l4pjrjsV_ym9N4dS2NGcx7OQZP3/view?t=4455"
     },
     "alsoIn": []
    },
    {
     "title": "Limit non-accredited investors to 35 in a 506 B offering",
     "teaches": "Members learn the cap on non-accredited investors and how LLCs count toward that limit.",
     "rule": "In a 506 B offering, you can take up to 35 non-accredited investors. If an LLC invests, each member is counted separately unless all members are accredited.",
     "speaker": "Bethany",
     "source": {
      "label": "02 EV Call 23 - Feb 18 2026 - Velocity Scorecard",
      "guest": null,
      "driveId": "1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1U-SND3NfJk5jQ6tmXEMgYdA60f_B3gqH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Adjust your W-4 withholdings to fund your next STR",
     "teaches": "How to keep the tax refund you expect from cost segregation and depreciation in your own bank account each month instead of lending it to the government interest-free, so you have capital ready to buy a short-term rental.",
     "rule": "If you know you'll get a large refund (e.g. $50K from cost-seg and depreciation), refile your W-4 to reduce withholdings so you keep roughly $4K/month. Hold the money; if you buy the STR, use it; if you don't, you still have it to pay the tax you always owed.",
     "speaker": "Kassidy",
     "source": {
      "label": "05 Office Hours 15 - Dec 18 2025 - Launch and Feed the Beast",
      "guest": null,
      "driveId": "161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/161BoBgCA_rpJLdyTAobhDOS9mNfF9X3x/view"
     },
     "alsoIn": []
    },
    {
     "title": "Buy management companies at 2–3x and roll them into a 6x collective",
     "teaches": "A roll-up play: acquire small STR management books cheaply, add value, and re-rate the combined entity.",
     "rule": "Buy management companies with ~25–30 units for 2–3x, then roll them into a larger collective where the combined company is worth ~6x — you pick them up at 3x and they're worth 6x instantly, plus you add value through better pricing, operations and management.",
     "speaker": "Patryk Swietek",
     "source": {
      "label": "06 EV Call 39 - Jun 10 2026 - The First 10 Minutes (guest Patryk Swietek)",
      "guest": "Patryk Swietek",
      "driveId": "1Teqbc-6H9Slc26Nd9363b7m2r65rNR07",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Teqbc-6H9Slc26Nd9363b7m2r65rNR07/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "4",
   "title": "Vehicles, Section 179 and equipment write-offs",
   "count": 4,
   "lessons": [
    {
     "title": "Section 179 and Bonus Depreciation on Vehicles",
     "teaches": "How to accelerate the entire value of a vehicle into a single-year write-off using Section 179 / bonus depreciation, and the two qualifying rules.",
     "rule": "To fully write off a vehicle, it must meet TWO rules: (1) it must weigh over 6,000 pounds — 6,001 pounds or more GVWR/GWVR — and (2) it must be considered a light truck or heavier, not a passenger vehicle. If it's over 6,000 pounds but classified as a passenger vehicle, you can only take up to $33,000 of accelerated depreciation.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    },
    {
     "title": "51% Business Use Requirement for Vehicle Write-Off",
     "teaches": "The business-use threshold a vehicle must meet to qualify for the write-off, and how commuting to a W2 affects it.",
     "rule": "The car must be used at least 51% for business use. Driving to your W2 does not count as business use. You only need to ensure over 51% of your miles are business miles for the year — it just has to be for this year. One trip to Austin this month could likely wipe that away.",
     "speaker": "Evan (call participant)",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    },
    {
     "title": "Vehicle Write-Off Math Example",
     "teaches": "The tax savings from writing off a qualifying vehicle in one year.",
     "rule": "If you buy a qualifying light truck for $100,000, you can put down as little as a $10,000 down payment, finance the rest, and write off the full $100,000 — which equals about $30,000 in tax savings if you're in the 30% tax bracket.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    },
    {
     "title": "Bonus Depreciation Timing Mirrors Short-Term Rental Cost Seg",
     "teaches": "How the timing of bonus depreciation on a vehicle parallels cost segregation on a short-term rental.",
     "rule": "If you take 100% bonus in the first year, technically it only has to be a short-term rental in that first year. If you carry over depreciation onto the next year and want to use it, it does still have to meet the requirements — but you could do it for six months.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "5",
   "title": "Exits: 1031, capital gains and the lazy 1031 window",
   "count": 12,
   "lessons": [
    {
     "title": "Stepped-up basis ends the deferral on 1031 exchanges",
     "teaches": "Depreciation and 1031 exchanges defer taxes during your life, but the deferral stops when the property transfers at death to heirs.",
     "rule": "1031 exchanges continue to defer taxes while you hold and roll properties, but when the property transfers after you pass away, the deferral stops because heirs receive a stepped-up cost basis.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV Call - Sep 04 2026 - Friday Call (moved)",
      "guest": null,
      "driveId": "1EmH6XLFrnplinXKpEd1lckR58hWHH_TM",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1EmH6XLFrnplinXKpEd1lckR58hWHH_TM/view"
     },
     "alsoIn": []
    },
    {
     "title": "1031 exchange eliminates taxes on sale",
     "teaches": "A 1031 exchange lets you sell a property and pay no taxes, including depreciation recapture, if you follow the rules.",
     "rule": "1031 exchanges allow you to sell the property and not pay any taxes like no taxes at all, including depreciation recapture. People say you defer the taxes, which is technically true, but Kassidy says live in the present.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 45-day 1031 identification window",
     "teaches": "After selling a property in a 1031 exchange, you have only 45 days to identify a replacement property.",
     "rule": "You have 45 days to go find another property. If you don't find something, you get the money back and it's like you didn't 1031 — it's just like you sold it.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Commercial properties make 1031s cleaner",
     "teaches": "Buying a commercial property like a hotel gives you a known close date, making the 1031 timeline much easier than residential-to-residential exchanges.",
     "rule": "With commercial property like a hotel, you get it under contract, do the PSA, and know your close date. A hotel close usually takes 90 days, so you can list your property, sell it, and 1031 directly into the commercial property. Residential-to-residential 1031s are harder because residential sellers hate waiting for you to sell something else.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "The lazy 1031: offset depreciation recapture in the same calendar year",
     "teaches": "How to use a replacement property to offset depreciation recapture when you fail or skip a 1031 exchange.",
     "rule": "The lazy 1031 is an unofficial term for selling a property, having depreciation recapture, and buying another property and putting it in service before December 31 of the same calendar year to offset that recapture. It is not a real 1031 exchange.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "The lazy 1031 has no 45-day identification deadline",
     "teaches": "The timing difference between a true 1031 exchange and the lazy 1031.",
     "rule": "With the lazy 1031 you do not need to find a property within 45 days; you just have to buy it and put it in service before the end of the calendar year, January 1 to December 31.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "The lazy 1031 is less efficient than a true 1031",
     "teaches": "Why a true 1031 exchange preserves more depreciation than the lazy 1031.",
     "rule": "With a 1031 exchange the depreciation recapture just goes away and the new property gets a whole new set of depreciation and cost segregation depreciation. With the lazy 1031 you must use depreciation from the new property to offset the recapture from the sold property, wasting depreciation that could have offset other income.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "1031 into a dream home: rent it out for two years before moving in",
     "teaches": "A strategy to 1031 investment property into a future primary residence without paying taxes.",
     "rule": "You can 1031 investment property into a property you eventually want as your primary residence. A good rule of thumb is to rent it out for two years before moving in. Longer is probably better. You must actually operate it as an investment property, advertise it, and make money on it.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "The 1031 identification and closing deadlines",
     "teaches": "A 1031 exchange defers tax but runs on a hard clock: 45 days to identify a replacement property and six months total to close.",
     "rule": "45 days to identify a replacement property, then roughly five more months (six months total) to close.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "The lazy 1031 — don't file the 45-day form if you're unsure",
     "teaches": "If you never file the 45-day identification form, you get your money back; if you file it and the deal falls through, your money is held until the end of the six months.",
     "rule": "If you don't fill out the 45-day 1031 form, you get your money back; if you file it and don't buy, your money is held until the end of the six months.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "The $92,000 capital gains bracket",
     "teaches": "There is a third capital gains bracket where reporting income under $92,000 means you pay no capital gains tax.",
     "rule": "If you make less than $92,000 a year, you don't pay any capital gains.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 27 - Mar 18 2026",
      "guest": null,
      "driveId": "1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1AyXDx1Owl3cwqsqxtDSEY2x6VhByFrBc/view"
     },
     "alsoIn": []
    },
    {
     "title": "Turn Instant Book on and build protections around it",
     "teaches": "How to get Airbnb promoting you while still screening risky guests.",
     "rule": "You absolutely have to have Instant Book on. Protect yourself with: automated follow-up messaging after booking that asks a question (cancel without penalty within 24 hours if they don't respond within ~12 hours and you feel uncomfortable), require ID/identity verification, set guest requirements, and a two-night minimum.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "6",
   "title": "Entities, banking and books that survive an audit",
   "count": 12,
   "lessons": [
    {
     "title": "S Corp for active income and W2 wage",
     "teaches": "How an S Corp is used for service-based or active income, paying yourself a W2 wage, and why that reduces self-employment taxes.",
     "rule": "An S Corp is a container for a service-based business taking in active income, and you pay yourself a W2 wage. As a W2 employee you pay about 7.5% employment taxes because your employer pays the other 7.5%; as a 1099 independent contractor or self-employed you pay the full 15%. With an S Corp, if you are going to make 100,000 dollars, you can pay yourself a lower salary, for example 30,000 dollars",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "Example: $300k S Corp profit offset by $300k real estate loss",
     "teaches": "Illustrates how a profitable S Corp and a loss-generating real estate holding company can net to zero on your personal tax return.",
     "rule": "If the S Corp makes $300,000 and the holding company has a $300,000 loss, those two returns combine into your personal return for zero dollars.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 24 - Feb 24 2026 - Four Ways Real Estate Pays You",
      "guest": null,
      "driveId": "1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1tJgfuWoFkP_b32dF5DzSRtnGdqxyz5HL/view"
     },
     "alsoIn": []
    },
    {
     "title": "Insurance sized to your net worth",
     "teaches": "Members learn the insurance fallback for residential and short-term rentals when no LLC is used.",
     "rule": "If it's just residential real estate, short term rentals, get the right insurance and your personal liability should be up to your net worth — a $2 million net worth means $2 million of personal liability insurance.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "The old five-properties-per-entity bundle",
     "teaches": "Members hear the historical practice of bundling cheap long-term rentals and why Kassidy does not recommend it.",
     "rule": "People used to put up to five properties in one company when buying long term rentals cheap, like 100 grand in Detroit, because the total equity was covered by insurance — I don't recommend this.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "LLC setup and maintenance costs",
     "teaches": "The dollar cost of forming and maintaining an LLC so members can budget for it.",
     "rule": "It's like 200 bucks to set up usually and about anywhere from 25 to 100 bucks a year to maintain.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "Name property LLCs after the address",
     "teaches": "A bookkeeping-friendly naming convention for property entities.",
     "rule": "Property LLCs get the address — 646 North Stewart — because it's easier to sort through, easier to see, and bookkeeping is easier; the holding company and service company get their own names.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "Wyoming LLC for anonymity and cheap filing",
     "teaches": "Why Wyoming is recommended for the holding company LLC and what the annual cost actually is.",
     "rule": "Use Wyoming for anonymity and cheap filing and minimal filing requirements. Wyoming registered agent renewal is about 25 dollars a year, with setup around 250 dollars. Nevada and Delaware have higher filing requirements.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 21 - Feb 5 2026",
      "guest": null,
      "driveId": "188On_OSrTrYWOPgyS5exNr6IdoB_dlZe",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/188On_OSrTrYWOPgyS5exNr6IdoB_dlZe/view"
     },
     "alsoIn": []
    },
    {
     "title": "S-Corp election reduces self-employment tax on business income",
     "teaches": "How electing S-Corp status on an LLC lets a business owner pay themselves a W-2 salary lower than actual profits, reducing the tax rate on the remainder taken as distributions.",
     "rule": "An LLC is the entity/box; the S-Corp or C-Corp is the tax election that determines how the IRS taxes you. As an S-Corp you pay yourself a W-2 salary substantially less than what you actually make; example given: on $100,000 top line, pay yourself a $30,000 salary, pay tax at the $30,000 rate, and take the rest as non-taxed distributions to invest in real estate and take depreciation.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "S-Corp vs employee net income comparison",
     "teaches": "A concrete dollar comparison showing the after-tax gap between operating as an S-Corp versus being an employee at the same income and expenses.",
     "rule": "Same income and same expenses: as an employee you are left with $40K; as an S-Corp you are left with $51K — an $11K difference, which over $40K is almost 30% more money.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Partnership losses flow through based on ownership percentage",
     "teaches": "When a property is held in an LLC taxed as a partnership, losses flow through to partners based on ownership percentage, and each partner's ability to deduct their share is tested at the individual level.",
     "rule": "If the property's held in an LLC taxed as a partnership, losses flow through on K-1s based on ownership percentage and each partner's ability to deduct their share depends on their own situation. It's tested at the individual level, not the entity level.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "06 EV Call 34 - Apr 22 2026 - The Permit Game",
      "guest": null,
      "driveId": "1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1yjyGjJcaAXgZ3v39sn_xE4QnxbkSFcL-/view"
     },
     "alsoIn": []
    },
    {
     "title": "Add a Wyoming holding company on top",
     "teaches": "The optional parent entity that sits above the property LLCs.",
     "rule": "You do not have to have a parent, but what they use is called a holding company, and that one lives in Wyoming for easy legal protection and anonymity. It costs 25 bucks a year to maintain; Kassidy uses Wyoming registered agent.com.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    },
    {
     "title": "Pay contractors by traceable method, not cash",
     "teaches": "Members learn to keep a paper trail for every contractor payment so expenses are legally deductible and defensible in an audit.",
     "rule": "Pay all contractors by check or traceable digital payment so you have a paper trail; if you take a deduction you should have sent them a 1099.",
     "speaker": "Kassidy",
     "source": {
      "label": "06 EV Call 36 - May 5 2026 - Run It Like a Micro Hotel (Erin)",
      "guest": null,
      "driveId": "1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1Dogga3Fu3VbJocf85RDIPnAWLt5p12ia/view"
     },
     "alsoIn": []
    }
   ]
  },
  {
   "n": "7",
   "title": "The 30-day year-end playbook — get it under contract",
   "count": 12,
   "lessons": [
    {
     "title": "You can revert to long-term rentals January 1 after taking the tax benefits",
     "teaches": "After placing units in service as short-term rentals before year-end, you can convert them back to long-term rentals on January 1 and still keep that year's tax benefits.",
     "rule": "If they're short-term rentals before the end of the year, then January 1 or January 2 you can turn them into long-term rentals again and you would have gotten the tax benefits for this year.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "The next 30 days are the year-end buying window",
     "teaches": "Why the last 30 days of the year matter for getting a property under contract to offset a looming tax bill.",
     "rule": "You have roughly the next 30 days to get a property under contract, closed, and set up to meet IRS requirements before year-end.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call - Sep 15 2026 - 30-Day Year-End Playbook",
      "guest": null,
      "driveId": "1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH/view"
     },
     "alsoIn": []
    },
    {
     "title": "Get under contract in 30 days to close and place in service by year-end",
     "teaches": "The year-end timeline that lets a property still reduce this year's tax bill.",
     "rule": "Get your property under contract within 30 days, close 30 days later, and get it in service 30 days after that — that sequence is what eliminates or at least reduces your tax bill for this year.",
     "speaker": "Kassidy Warren",
     "source": {
      "label": "07 EV Call - Sep 15 2026 - 30-Day Year-End Playbook",
      "guest": null,
      "driveId": "1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1PAroPnxzSPijECg5ZGAMyaZE8bAgEGOH/view"
     },
     "alsoIn": []
    },
    {
     "title": "The lazy 1031: stay under the capital gains threshold",
     "teaches": "Members learn how to avoid federal capital gains tax by keeping reportable income below the threshold in a year they sell appreciated assets.",
     "rule": "If you get your reported AGI below roughly $92K (married), you pay no federal capital gains tax — so sell assets early in the year and buy STRs to push income down.",
     "speaker": "Kassidy",
     "source": {
      "label": "07 EV Call 14 - Dec 8 2025 - Tax Leverage Hierarchy",
      "guest": null,
      "driveId": "1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1RIMlg5F1WoEb4RFnC07CGnKs4jiiZsTb/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use the 7-day rule for STR tax treatment",
     "teaches": "To qualify as a short-term rental for tax purposes, the average guest stay must be 7 days or less.",
     "rule": "The average nightly stay must be 7 days or less to qualify as a short-term rental for tax purposes. This is easy to maintain as long as you're not using it as a midterm rental.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV Call 1 - Sep 10 2025 - Velocity of Money",
      "guest": null,
      "driveId": "1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi",
      "startSec": 3770.6,
      "at": "1:02:50",
      "watch": "https://drive.google.com/file/d/1RDm95JmkZSabfJNbthOTdpIbVIcFFfRi/view?t=3770"
     },
     "alsoIn": []
    },
    {
     "title": "Estimate tax savings at 20-30% of purchase price",
     "teaches": "A quick conservative rule for projecting first-year tax write-offs.",
     "rule": "Tax savings from a short-term rental are roughly 20-30% of the purchase price, depending on your income. On a $1M property that's $200K-$300K of write-off against W2 income.",
     "speaker": "Kassidy",
     "source": {
      "label": "00 EV call 47 - Aug 12 2026 - Velocity Money Four Levers",
      "guest": null,
      "driveId": null,
      "startSec": null,
      "at": null,
      "watch": null
     },
     "alsoIn": []
    },
    {
     "title": "1031 exchange to avoid depreciation recapture tax",
     "teaches": "Members learn that selling without a 1031 exchange triggers depreciation recapture taxed as ordinary income, which can exceed the cash received from the sale.",
     "rule": "If you sell a short-term rental without a 1031 exchange, all depreciation taken is recaptured and taxed at your ordinary income rate. Example: $400,000 depreciation at 32% = $120,000 tax, which can be more than the $100,000 cash you receive from the sale.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "1031 from residential to commercial is cleaner",
     "teaches": "Members learn why 1031 exchanging into a commercial property like a hotel is easier than residential-to-residential because you control the closing timeline.",
     "rule": "With commercial property, you have a PSA and a known closing date (often 90 days), so you can list and sell your property within the 45-day identification window. Residential-to-residential 1031s are harder because buyers won't wait for your sale.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use a 1031 to trade up and build equity",
     "teaches": "Members learn how repeated 1031 exchanges can turn small equity into large equity over time.",
     "rule": "Trade up from residential to commercial properties using 1031 exchanges to defer taxes and boost value. Example: a $65,000 HELOC on a primary residence was used to buy land, which was sold and 1031 exchanged into a property now worth $800,000 in equity.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "Use the lazy 1031 to wipe out depreciation recapture",
     "teaches": "If you sell a property and fail or skip a formal 1031, you can still offset the depreciation recapture by buying another property in the same calendar year.",
     "rule": "The lazy 1031: sell a property, then buy enough property to offset all your income including the depreciation recapture, all within the same calendar year (Jan 1 to Dec 31). No 45-day identification window applies.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "A 1031 is more efficient than the lazy 1031",
     "teaches": "Why the formal 1031 beats the lazy 1031 even though the lazy 1031 is easier.",
     "rule": "With a 1031 the recapture just disappears and you get a whole new set of depreciation and cost segregation on the new property. With the lazy 1031 you must spend some of the new property's depreciation just to cover the recapture from the property you sold, so it is less efficient.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    },
    {
     "title": "1031 into your future dream home",
     "teaches": "A strategy to move investment property equity into a personal residence tax-deferred.",
     "rule": "1031 investment property into a home you want to live in, rent it out for at least two years operating it as a real investment (advertise it, make money on it), then move in. Longer than two years is better.",
     "speaker": "Kassidy",
     "source": {
      "label": "02 EV Call 22 - Feb 11 2026 - IRR and ROE (guest Brian Pate)",
      "guest": "Brian Pate",
      "driveId": "1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS",
      "startSec": null,
      "at": null,
      "watch": "https://drive.google.com/file/d/1YoCEgjgLoBkRQaH2Ps1n2kuOYRUF0UQS/view"
     },
     "alsoIn": []
    }
   ]
  }
 ]
};

export default tax;
